### ISSUE TITLE
Bolt custom receiver

### ISSUE THREAD

**Issue by B0ER** [slackapi/node-slack-sdk#1043]
### Description

Don't work event listener with interactive listener in bolt.
I wrote my receiver and set it on bolt.
How can I add other listeners to bolt?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [X] `@slack/bolt`
- [ ] `@slack/web-api`
- [X] `@slack/events-api`
- [X] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

**Comment by stevengill** [comment]
Hey @B0ER,

Sorry I'm a little confused by your issue here.

For Bolt-js, you don't need to use `events-api` and `interactive-messages` packages since bolt includes code to handle those payloads. You would use `events-api` and `interactive-messages` if you weren't using bolt. 

Could you provide more information about what libraries you are using?

**Comment by stevengill** [comment]
Going to close this issue due to inactivity. Please feel free to reopen the issue if it isn't resolved.
