### ISSUE TITLE
"client" scope for RTM api

### ISSUE THREAD

**Issue by VinceWang92** [slackapi/node-slack-sdk#1104]
> @ptmt is your app already distributed in the App Directory? One limitation I’m aware of is that the `client` scope is not available for App Directory apps.
> 
> For the record, the technique I’ve used to successfully request the client scope is just a matter of pointing the browser to the OAuth authorization URL with `client` in the `scope` GET param (query string).

@aoberoi  I was trying to pointing the browser to the OAuth authorization URL with client in the scope GET param, but the client scope is still cannot be added. Also I made sure the traditional scope is not enabled. Can you tell me if slack still has a way to enable the "client" scope for rtm api

_Originally posted by @VinceWang92 in https://github.com/slackapi/node-slack-sdk/issues/663#issuecomment-705890571

**Comment by seratch** [comment]
@VinceWang92 It should be still available if you ask for no other scope at the same time.

**Comment by code-guru** [comment]
You need to make sure the following to client scope to work
1. You have create a *classic app* and not a new slack app
2. use slack *oauth* v1 instead of v2. 
3. add a redirect url
4. use following url to get oauth code from user
https://slack.com/oauth/authorize?client_id={your-client-id}&scope=client&redirect_uri={your-redirect-url}

**Comment by seratch** [comment]
@code-guru Thanks for sharing your knowledge 👍 

Let us close this issue due to its inactivity.
