### ISSUE TITLE
Include "Retry-After" in the "A rate limit was exceeded." error

### ISSUE THREAD

**Issue by gajus** [slackapi/node-slack-sdk#1119]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

https://github.com/slackapi/node-slack-sdk/blob/0963851e914dbc0a59d9f80305705bda2d0b9bd8/packages/web-api/src/WebClient.ts#L337

The current rate limit error is missing `retry-after` instructions.

The latter information is needed to device smart back-off strategies.

Example code:

```js
await slackWebClient.users.getPresence({
    token: slackUser.accessToken,
    user: slackUser.foreignSlackUserId,
});

```

Error:

```
 Error: A rate limit was exceeded.
          at /Users/gajus/Documents/dev/[..]/node_modules/@slack/web-api/src/WebClient.ts:337:19
          at run (/Users/gajus/Documents/dev/[..]/node_modules/p-queue/dist/index.js:163:29)
```

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

**Comment by gajus** [comment]
Related, but a different issue, there is no constant "error code".

Using `error.message === "A rate limit was exceeded."` is a not a great way to detect the error.

**Comment by gajus** [comment]
On a related note, it is not clear where the `retriesLeft` and `attemptNumber` properties coming from.

```js
Error: A rate limit was exceeded.
    at /Users/gajus/Documents/dev/[..]/node_modules/@slack/web-api/src/WebClient.ts:337:19
    at run (/Users/gajus/Documents/dev/[..]/node_modules/p-queue/dist/index.js:163:29) {
  attemptNumber: 1,
  retriesLeft: 0
}

```

Just by looking at the source code, it appears that they originate from https://github.com/sindresorhus/p-retry.

**Comment by aoberoi** [comment]
If I understand this correctly, the issue is that after all retries have been exhausted and the request still fails, you want to see as more information about the last attempt (specifically, the value of `retryAfter`).

Although it's not set up this way today, I think it would make sense to use the `WebAPIRateLimitedError` code for the eventual error. This error type contains a `retryAfter` property, and we'd have to fill that value in.

The `attemptNumber` and `retriesLeft` properties should still be on the error (in order to ensure backwards compatibility). This shouldn't require any additional work; I think `p-retry` will take care of adding those properties for us.

Does this sound right to you?

If you used the `rejectRateLimitedCalls: true` option, then you'd get this sort of an error already. We previously hadn't considered that you'd want this data if the `WebClient` was handling retries on your behalf. How would you use this data if not to generate another retry? If you are willing to rewrite your own retry logic, is the better solution to just use the option?

**Comment by gajus** [comment]
I was now aware of `rejectRateLimitedCalls: true`.

I had my client configured to:

```js
const web = new WebClient(token, {
  retryConfig: { retries: 0 },
});

```

I only now saw the documentation that says:

> Note: If an API call results in a rate limit being exceeded, you might still notice the client automatically retrying the API call. If you’d like to opt out of that behavior, set the `rejectRateLimitedCalls` option to `true`.

This works for my use case.

Given that `rejectRateLimitedCalls` option exists, I don't see an action here.

Maybe an improvement would be just to throw an error if someone mistakenly set `{ retryConfig: { retries: 0 }, }`.
