### ISSUE TITLE
Use the proper Response types for Web API methods

### ISSUE THREAD

**Issue by rr-codes** [slackapi/node-slack-sdk#1213]
### Description

All the Web API methods have their result types in https://github.com/slackapi/node-slack-sdk/tree/main/packages/web-api/src/response , however these types are not being used as the types for `Method<P, R>`. Instead, the general `WebAPICallResult` type is used. This should be updated to use the types that are already present.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @rr-codes, those types will be used since the next minor version (6.2)! The RC version is already available. Please try it out and let us know if you have feedback on it: https://github.com/slackapi/node-slack-sdk/pull/1210#issuecomment-822121200

If everything is clear here, could you close this issue?

**Comment by rr-codes** [comment]
ooh awesome, thanks so much!!
