### ISSUE TITLE
When closing a Modal that uses an External Select, an "Are you sure" message is shown

### ISSUE THREAD

**Issue by rr-codes** [slackapi/node-slack-sdk#1237]
### Description

In a typical modal, if no changes are made to it, closing the modal does not prompt any message.

However, if the modal uses an external select element, when clicking the close button on the modal, Slack gives an "Are you sure?" message, which shouldn't be the case.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: `6.2.0`

node version: `12.19.0`

OS version(s): N/A

#### Steps to reproduce:

1. Create a basic slack app that opens a modal upon an action occurring. The modal should have an external select element within it.
2. Click the modal's `Close` button
3. See that an "Are you sure?" message is shown, even when no changes are made.

#### Expected result:

For it to exhibit the same behaviour as a normal modal.

#### Actual result:

It shows an "Are you sure" message

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by mwbrooks** [comment]
Hey @rr-codes, thanks for finding this inconsistency!

Since this is a Slack API (Block Kit) issue, we're unable to fix it in `slackapi/node-slack-sdk`. However, it's still super valuable to have these issues reported.

**I've gone ahead and reported your issue internally with the Slack API team and linked to this GitHub issue.**

We can't guarantee when this will be looked at by the team, so I'm going to close our GitHub issue. If anyone else experiences the issue, feel free to leave a comment or add a reaction. It helps to add weigh and priority to it!
