### ISSUE TITLE
Not possible to set user Profile status

### ISSUE THREAD

**Issue by adelin-b** [slackapi/node-slack-sdk#1291]
### Description

It is not clear how to set custom users status with `client.users.profile.set`, it is only possible to do it for the user that did the boltjs installation but not for other users on non-paid workspace, yet google calendar app is able to automaticaly update status even in non-paid slack workspace.

The only info I found on the topic is https://stackoverflow.com/questions/53094180/changing-status-of-other-users-on-a-free-plan-slack

> You could collect tokens from all you users and then use those to change the status for each user. For that each user will have to install your app though OAuth once. This will create individual tokens for each user,

Yet when installing google calendar app on a free-plan workspace we are not asked to install the app through OAuth. 

So how to do that ?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] question

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.
---

#### Packages:

Select all that apply:

- [x] `@slack/web-api`

**Comment by stevengill** [comment]
Hey @adelin-b, once you install the google app on a workspace, each user has to authenticate with it as well. This is how google is able to customize for each user (it will show me my calendar, not yours). 

This has nothing to do with paid vs non paid slack workspaces. 

[users.profile.set](https://api.slack.com/methods/users.profile.set) requires user tokens. When one person installs it to the workspace, you save the user token for that person. That is why you are only able to update the status of the person who installed the app. In your example, you need to collect `user tokens` from everyone. What this looks like:

1) Install the app to the workspace (assuming you setup OAuth and use that to install),
2) Get every user to authenticate using OAuth. You could have the app DM everyone asking them to authenticate (this would essentially get them to run through their own oauth flow). Or you could also have the app home show a screen about authenticating instead of DMing everyone (a little less invasive). This way, users who navigate to the app home would be able to opt into authenticating.

**Comment by seratch** [comment]
👋 @adelin-b, do you still need help here? We will close this issue after waiting for your response for a few more days.

**Comment by seratch** [comment]
Let us close this issue now but please feel free to write in whenever you have anything further to ask/discuss here!
