### ISSUE TITLE
Thread message doesn't work as expected for the new app

### ISSUE THREAD

**Issue by zhiKong-ibm** [slackapi/node-slack-sdk#1295]
### Description
I was developing an app using the classic app with the bot enabled. And when the origin message is a reply itself, the bot can reply to that message as expected with the chat.postMessage method.
Now I'm trying to migrate this app to the slack new app. Same scenario, the thread message doesn't work as expected with the new slack app bot token.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version:
@slack/web-api@6.3.0

node version:
v12.16.3

OS version(s):
Red Hat Enterprise Linux 8.3

#### Steps to reproduce:

1. Send a message to the bot in one thread, Let's assume this message is message A which in the attachment A is message `@bnzdev03kong help`.
2. The bot App get the message and set the reply as follow. And the thread_ts is the ts value from message A which should be the parent ts value as the guide said.
```
{
    "type": "block",
    "message": {
        "channel": <channel Id>,
        "blocks": [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "Thread message example"
                }
            }
        ],
        "replace_original": false,
        "thread_ts": <messageA.ts>,
        "text": "example"
    }
}
```
3. Reply with the chat.postMessage method with different bot tokens, the classic app bot user token and the new app bot user token.

#### Expected result:
When using the new app bot user token, only reply to message A in the thread like attachment A 

#### Actual result:
When using the new app bot user token, the reply to message A will perform two actions.  First it'll reply in that thread as expected see attachment A, but also it will post Message A in that channel again see message marked with red rectangle in attachment B.

#### Attachments:
Attachment A:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/83753335/127275807-3cf54a23-721d-4120-ac4a-711f1cb147c8.png">
Attachment B:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/83753335/127276095-83161df3-ed91-4ca9-ba58-60b5ee7d6231.png">

**Comment by zhiKong-ibm** [comment]
Just one more question. Is the new app bot token doesn't support to reply a reply in thread?
There is a comment in this guide. https://api.slack.com/messaging/sending#threading
which said: `First, make sure the message you want to reply to isn't a reply itself, as shown in our retrieving messages guide.`

**Comment by filmaj** [comment]
Hi @zhiKong-ibm!

I am trying to reproduce your issue but having trouble with it. I am also a bit confused by your report. Could you please clarify in your report which users are the bot users, and which one is the 'classic' bot vs. which one is the 'new app' bot? Looking at your attachments, it looks like the users `bnzdev03` and `bnzdev03kong` are apps - and both successfully replied in the thread as desired. However, the extra message in the channel as described in your Attachment B is not from the apps - but rather from a different, third account, which is not an app/bot account, but seems like a regular user account?

Could you clarify your expectations and elaborate on what the issue is?

**Comment by filmaj** [comment]
Here are the relevant bits in an app I have created where I cannot reproduce the issue you describe, @zhiKong-ibm . It is a node Slack app using the `@slack/web-api` package version 6.3.0.

First, my event handler has this code:

```
  if (body && body.event && body.event.type) {
    switch (body.event.type) {
      case 'app_mention':
        let payload = {
          channel: body.event.channel
        };
        if (body.event.thread_ts) {
          payload.thread_ts = body.event.thread_ts;
          payload.text = 'Responding to in-thread app mention - inside the thread';
        } else {
          payload.thread_ts = body.event.ts;
          payload.text = 'Responding to parent message app mention - but inside the thread';
        }
        await arc.events.publish({
          name: 'post-message',
          payload
        });
        break;
      default:
        break;
    }
  }
  return {
    statusCode: 200,
    headers: {
      'cache-control': 'no-cache, no-store, must-revalidate, max-age=0, s-maxage=0',
      'content-type': 'text/plain'
    },
    body: ''
  };
```

The `body` variable above is the JSON payload received from the [Events API](https://api.slack.com/events?filter=Events). In particular, in the `switch` statement, I listen for the [event type `app_mention`](https://api.slack.com/events/app_mention). I then construct a `payload` object that will be fed into the [Web API's `chat.postMessage` API](https://api.slack.com/methods/chat.postMessage). The payload contains a `thread_ts` property that is _either_ a) the `app_mention` event's `thread_ts` property, if it exists, _or_ b) the `app_mention` event's `ts` property. This way, if the bot is mentioned in a parent message, the bot sends a threaded reply to the parent message. Otherwise, if the bot is mentioned from within a threaded message, then the bot sends a threaded reply within the same threaded message.

For posterity, the `post-message` topic I "publish" to is an [AWS SNS publish/subscribe topic](https://aws.amazon.com/sns/) whose sole job is to execute the `chat.postMessage` Slack Web API call. The reason I separate answering the HTTP POST from the Slack Events API from posting a chat message in this way is to honour [the Slack Event API's recommendation to offload background tasks to an asynchronous worker and respond to the Events API over HTTP with a 200 status code as quickly as possible](https://api.slack.com/apis/connections/events-api#the-events-api__responding-to-events). The code for this SNS function is:

```
const arc = require('@architect/functions');
const { WebClient } = require('@slack/web-api');
const TOKEN = 'xoxb-super-secret'; // don't hard-code your tokens! but I am being lazy for the purposes of this demonstration
const web = new WebClient(TOKEN);

exports.handler = arc.events.subscribe(async function subscribe (event) {
  let { text, thread_ts, channel } = event;
  await web.chat.postMessage({ channel, text, thread_ts });
});
```

(For those curious, I am hosting this app on AWS using a combination of API Gateway, Lambda and SNS using [architect](https://arc.codes) - happy to share the full application code if that is helpful for anyone)

With the above setup, I only get the bot to respond within threads, and it never posts parent messages to the channel.

I hope this is helpful! If it resolves the problem you are having, please kindly close this issue. If not, I am happy to further assist.

**Comment by zhiKong-ibm** [comment]
Hi filmaj,
I just tried your solution it worked, and the problem is related with the thread_ts value.
payload.thread_ts = body.event.thread_ts;
This works, but what I used is the ts value 
payload.thread_ts = body.event.ts;

Thank you. I'll close this comment.
