### ISSUE TITLE
Huddle API Support

### ISSUE THREAD

**Issue by matthiassb** [slackapi/node-slack-sdk#1353]
Will support for Huddle API be made available?

**Comment by mwbrooks** [comment]
Hey @matthiassb 👋🏻 It's great to hear that you're interested in the Huddles API.

The Huddles team has not released a public API, but it's been a highly requested feature that they're discussing. The [Slack API Changelog](https://api.slack.com/changelog) is the best place to keep an eye on for its release announcement.

💡 What would you like to do with the Huddles API? If you have a specific needs, I can pass it onto the Huddles team so that they are aware of it!

**Comment by matthiassb** [comment]
Hi @mwbrooks a music bot would be one scenario, an assistant bot that supports voice commands would be another

**Comment by seratch** [comment]
Hi @matthiassb, we'll internally share your feedback with the product team. Thanks a lot for sharing your use case!

All the server-side issues/product plans are managed in our internal issue tracker and we have been escalating many issues like this. As this issue tracker is for the client-side SDK, we are unable to continue discussing this topic and/or sharing the updates on the server-side in a timely manner. For this reason, let us close this issue here. To check the updates on the platform, as Micheal mentioned, please check our changelog page.

Thanks again for your time and interest here!
