### ISSUE TITLE
Work with other OSS projects on transitioning over to use >= 2.0.x

### ISSUE THREAD

**Issue by l12s** [slackapi/node-slack-sdk#141]
Rough plan here is to have the `>= 2.0.x` release out for 2-4 weeks to shake out any bugs and then talk to folks who depend on the old `slack-client` module about what a transition plan would look like to upgrade.

**Comment by gregorskii** [comment]
Hi there,

I am currently trying to update to the new client. I am running into some things that may be helpful.

The main thing I am seeing so far is that the new client is simply a client, it is more low level than the previous library and does not afford some of the same conveniences.

That could be the goal entirely, but I am finding it is a bit more complex to use it in a simple application that the previous library and may necessitate a wrapper library to make it more use friendly. I could be wrong, or maybe this is premature. But this is what I am finding... :)

If I am wrong in any of these assumptions below please correct me, and maybe update the documentation.

Thank you,

Greg

---
I see the new client does not provide the same event wrapper as the old, where it does not export a eventing `slack` object that has:

```
slack.on('open', function() {});
slack.on('message', function(message) {});
slack.on('teamJoin', function(user) {});
slack.on('error', function(error) {});
```

After connecting to the client in the old version using:

```
var autoMark = true;
var autoReconnect = true;
var slack = new Slack(process.env.SLACK_TOKEN, autoReconnect, autoMark);
```

One was off to the races sending and receiving messages. It is quite confusing using the new library to get running quickly.

The new project includes the `CLIENT_EVENTS` and `RTM_EVENTS` enumerations but requires that one wrap a new object to include the same eventing that older clients were expecting:

```
module.exports = function() {
    var events = require('events'),
        util = require('util'),
        RTM_EVENTS = require('@slack/client').RTM_EVENTS
    ;

    var Slack = function(rtm) {
        events.EventEmitter.call(this);

        // Proxy RTM event to slack object event
        rtm.on(RTM_EVENTS.MESSAGE, function(message) {
            this.onMessage(message);
        }.bind(this));
    };

    util.inherits(Slack, events.EventEmitter);

    Slack.prototype.onMessage = function(data) {
        this.emit('message', data);
    };

    return Slack;
};
```

The goal of this change presumably is to extract the rtm client from a `slack` helper object with eventing. But it is quite confusing to push the RTM_EVENTS actions back on the object in a usable way.

---
The new client does not automatically merge the connection data with the returning object.

The old client had keys like `slack.self.name` where the new client returns similar data in the `rtmStartData` object after calling `rtm.start()`. The data that is returned in that object could be merged with a parent object like the previous library.

---
The new client has an event that is triggered on connect, (which was my main reason for switching to the new), this event ideally (and all events) would be better if they returned a promise, or a callback, depending on how they are called.

Example of what I am doing now:

```
module.exports = function(log) {
    var Promise = require('bluebird'),
        RtmClient = require('@slack/client').RtmClient,
        CLIENT_EVENTS = require('@slack/client').CLIENT_EVENTS,
        token = process.env.SLACK_TOKEN,
        rtm = new RtmClient(token, {logLevel: 'error'}),
        Slack = require('./slack')(log),
        _ = require('lodash')
    ;

    if (!token) {
        log.fatal('Missing slack token');
    }

    return {
        connect: function() {
            return new Promise(function(resolve, reject) {
                rtm.on(CLIENT_EVENTS.RTM.AUTHENTICATED, function(rtmStartData) {
                    var slack = new Slack();
                    resolve(_.extend(slack, rtmStartData));
                });

                rtm.on(CLIENT_EVENTS.RTM.UNABLE_TO_RTM_START, function(err) {
                    reject(err);
                });

                rtm.start();
            });
        }
    }
}
```

```
interfaces.slackRtm.connect()
    .then(function(slack) {
        log.info("Welcome to Slack. You are @" + slack.self.name + " of " + slack.team.name);
    })
    .catch(function(error) {
        log.fatal(error, 'ERROR Unable to start Slack RTM');
    })
;
```

Promises are useful because they can be chained with existing app startup events that utilize Promises.

---

The new library drops some of the helper functions that were used to get channels to send messages back on:

```
Client.prototype.getUserByID = function(id)
Client.prototype.getUserByName = function(name)
Client.prototype.getChannelByID = function(id)
Client.prototype.getChannelByName = function(name)
Client.prototype.getDMByID = function(id)
Client.prototype.getDMByName = function(name)
Client.prototype.getGroupByID = function(id)
Client.prototype.getGroupByName = function(name)
Client.prototype.getChannelGroupOrDMByID = function(id)
Client.prototype.getChannelGroupOrDMByName = function(name)
Client.prototype.getUnreadCount = function()
Client.prototype.getChannelsWithUnreads = function()
```

These functions were used in the old libraries example 'onMessage' callback to determine the user and the channel of the incoming message, it could then use these channels and users to send back messages:

```
var ts = message.ts;
var type = message.type;
var userID = message.user;
var text = message.text;

var channel = slack.getChannelGroupOrDMByID(message.channel);
var user = slack.getUserByID(userID);
var userName = (user && user.name) ? '@' + user.name : 'UNKNOWN_USER';
var isMention = slackHelpers.isDirect(slack.self.id, message.text);
var isDirect = channel.id.charAt(0) === 'D';
var isUserBot = (userID === slack.self.id);
```

**Comment by l12s** [comment]
Ok, quick response from me:

# Other libraries

The idea is to eventually support botkit and hubot-slack with this library. I wanted to have this in use for a little while before that though, to find any bugs / issues.

# Event Wrapping

I don't understand what you mean here. Can you explain a bit more about why you would wrap the client object here? The RTM client is a subclass of [eventemmiter3](https://github.com/primus/eventemitter3) and as you show in your snippet, you can listen to events it emits directly.

# Promises

These are coming, see https://github.com/slackhq/node-slack-client/issues/139

# Data access and helper functions

The new client breaks out the responsibility for storing information and managing connections into two objects:
- the [RTM client](https://github.com/slackhq/node-slack-client/blob/master/lib/clients/rtm/client.js)
- the [MemoryDataStore](https://github.com/slackhq/node-slack-client/blob/master/lib/data-store/memory-data-store.js)

The MemoryDataStore has the old methods like getChannelGroupOrDmByID and, if you attach one, will cache the `rtm.start` data.

You can attach that data-store by creating a client like:

```js
var rtm = new RtmClient(token, { logLevel: 'debug', dataStore: new MemoryDataStore() });
rtm.start();
```

... and then access the data-store like:

```js
var channel = rtm.dataStore. getChannelById(channeld);
console.log(channel);
```

Also, one request: if you have further questions, could you create a new issue? This is intended to track the work that's involved in getting botkit etc. using this library, so isn't a great location for this conversation.

**Comment by gregorskii** [comment]
@l12s,

Will not respond here. From the comment it seemed like it could be a discussion per "then talk to folks who depend on the old slack-client module about what a transition plan would look like to upgrade."

Was prematurely chiming in then.

Will review these notes. Does indeed look like the same functionality is in place. Likely the general OSS community just need to give it time for the documentation to get added/kinks to be worked out.

Thanks

**Comment by Lokeh** [comment]
In general I find the lack of documentation the hardest part. Data stores and models are not explained anywhere, and in general I find myself needing to read source code in order to get much done.

**Comment by l12s** [comment]
Yep, that's a totally fair point. Getting more docs in place is definitely something we need to work on.

**Comment by aoberoi** [comment]
this issue contains some valuable information, but i've tried to link to it from more specific issues that can be individually worked on for progress.

the original intent was to track the progress of hubot and botkit adoption. hubot is now built on top of this package 🎉 , while botkit is not and doesn't plan on it (i think botkit's needs are to be a general abstraction on top of many platforms and this package is not well suited to address that need). closing for these reasons.
