### ISSUE TITLE
Update "Developing Slack apps locally" document page to mention Socket Mode

### ISSUE THREAD

**Issue by seratch** [slackapi/node-slack-sdk#1434]
"Developing Slack apps locally" document page should mention Socket Mode.

### List any relevant URLs

- https://slack.dev/node-slack-sdk/tutorials/local-development
- https://github.com/slackapi/node-slack-sdk/blob/main/docs/_tutorials/local_development.md

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
This whole guide is pretty out of date... references to App Config page UI elements do not exist anymore (i.e. "Click Bot Users on the left side bar").. think there's a lot to change in this document (and possibly others). What's more, a majority of the document is just focussed on setting up a request URL for an app. So, if we want to mention Socket Mode, I think this page needs a significant restructure.

Anyone else from the team has ideas on how to go about modernizing this page?

Some of my ideas:

- Need to talk about app-level tokens and not just bot and user tokens
- Do we want to still mention both request-URL-based local development, or do we want to go 100% socket mode? If both, then I think we could maybe split the page up into two main sections, based on whether using HTTP or Socket Mode? Each of these would require different app setup / app config page settings.
- The document contains many, kind of random, references to the sub-packages of node-slack-sdk. I.e. when setting up interactive components is mentioned in the doc, there is a callout "The `@slack/interactive-messages` package is used for Interactive Components". I found this jarring - anyone else? Like, the call out to the package isn't actionable and at least for me I found it distracting? Like do I need to pay attention to this package and read about it now in order to set up local development, or no? I think we should remove them... what do others think?
- Is there another local development tutorial / article from any of our other packages that perhaps has a better structure to follow that we can mostly copy over and duplicate under the node-slack-sdk docs? Or perhaps more broadly, I'm not sure how much this tutorial is node-slack-sdk-specific, so maybe we can even eliminate it all together and link to a more generic 'how to local dev' article somewhere? Like, do we want to recreate a "how to local dev" article for the node slack SDK, python SDK, java SDK, each flavour of bolt, etc.?

**Comment by seratch** [comment]
@filmaj Thanks for sharing the thoughts here!

Let me share my thoughts on your comment as below ... but now I came to think that we may want to navigate this page visitors to bolt-js getting started docs instead. We have both Socket Mode and HTTP Mode pages.

* https://slack.dev/bolt-js/tutorial/getting-started
* https://slack.dev/bolt-js/tutorial/getting-started-http

If we update this page, perhaps we will repeat mostly the same things in the page. Thus, deleting most of the page content and having the links to the bolt-js documents would be clearer and also it should be easier to maintain for us in the long run.

What do you think?

(comments on your points)

>Do we want to still mention both request-URL-based local development, or do we want to go 100% socket mode? 

For some use cases such as testing an OAuth app, Request URL way is still needed. That being said, for beginners, recommending Socket Mode first would be reasonable.

>If both, then I think we could maybe split the page up into two main sections, based on whether using HTTP or Socket Mode? Each of these would require different app setup / app config page settings.

Yes, you're right. We are already doing this in the bolt-js getting started guides.

>The document contains many, kind of random, references to the sub-packages of node-slack-sdk. I.e. when setting up interactive components is mentioned in the doc, there is a callout "The @slack/interactive-messages package is used for Interactive Components". I found this jarring - anyone else? Like, the call out to the package isn't actionable and at least for me I found it distracting? Like do I need to pay attention to this package and read about it now in order to set up local development, or no? I think we should remove them... what do others think?

Yes, we can simply remove the deprecated modules. Also, recommending bolt-js is far easier-to-understand for developers.

>Like, do we want to recreate a "how to local dev" article for the node slack SDK, python SDK, java SDK, each flavour of bolt, etc.?

I don't think that we should copy this kind of page to other SDK documents. I think that, as this page is already in Google search engine index, we'd like to keep the URL at least with meaningful links, though. Ideally, we may want to have a unified page for this topic in api.slack.com but we can discuss this internally and separately.

**Comment by filmaj** [comment]
> If we update this page, perhaps we will repeat mostly the same things in the page. Thus, deleting most of the page content and having the links to the bolt-js documents would be clearer and also it should be easier to maintain for us in the long run.

To me this makes a lot of sense, and while it can be a less-than-ideal experience to click out of the article to go to a 'shared' section on e.g. setting up app basics for socket mode local development, at least it would be accurate and apply to all the SDKs equally - not to mention the maintainability increase as you mention.

> For some use cases such as testing an OAuth app, Request URL way is still needed. That being said, for beginners, recommending Socket Mode first would be reasonable.

Great point. To me this says that the focus for a local development article should _start_ with socket mode, but leave a section near the end to explain when you may want to use request URLs to test only certain parts of your app, and how to set the app up for that kind of testing.

> Yes, we can simply remove the deprecated modules. Also, recommending bolt-js is far easier-to-understand for developers.

100% agreed.

> I don't think that we should copy this kind of page to other SDK documents. I think that, as this page is already in Google search engine index, we'd like to keep the URL at least with meaningful links, though. Ideally, we may want to have a unified page for this topic in api.slack.com but we can discuss this internally and separately.

Good point on search engine indexing, I did not think of that...

Thanks for this discussion @seratch. With this information, tomorrow in my morning I can look at this article again, and the relevant parts from the bolt-js guide, to draft a rewrite of this article.
