### ISSUE TITLE
State verification doesn't work in @slack/bolt

### ISSUE THREAD

**Issue by piboistudios** [slackapi/node-slack-sdk#1483]
State verification does not work. And not only does it not work but turning it off in the `installerOptions` causes `@slack/oauth` to randomly fail with some other error (`StateStore is not properly configured`) that I can't find anywhere because none of the errors have error codes and they all only include language that's meaningful to the smooth-brains that wrote the SDK

Normally I'd provide better details but you couldn't even be bothered to provide accurate documentation so give it a shot yourself and figure it out.

Most frustrating integration I've ever had to do. Should be ashamed of yourselves.

Anyways I'll end up just writing my own oauth redirect URL since the one provided out of the box is broken one way or the other and I'm tired of staring at config and source code to find scarce information that should be in the docs.

**Comment by piboistudios** [comment]
Apparently flipping `installerOptions.legacyStateVerification` to `true` resolves this issue....

Yet another option not documented anywhere? I don't even know what this does, I am literally just flipping options messing around.

**Comment by mwbrooks** [comment]
Hey @piboistudios, super sorry to hear about your frustrations!

We were taking a moment to double-check the OAuth examples, because there have been recent changes (PR https://github.com/slackapi/bolt-js/pull/1391). However, it looks like you've unblocked yourself!

The `legacyStateVerification` option is documented on the [OAuth Installer Options docs](https://slack.dev/node-slack-sdk/reference/oauth#installpathoptions). It's a recent addition since we did a major refactor to simplify managing the state:
> Whether to skip checking browser cookies for state OAuth parameter verification. Defaults to false. Enabling this option is not recommended! This is intended to be used only for backwards-compatibility with versions 2.4 and older.

❓ **To help us out, would you mind sharing your @slack/bolt version?** This will help us understand what version of the @slack/oauth package you're using.

Thanks!
Michael
