### ISSUE TITLE
Is it possible to make a modal's "submit" button open a url?

### ISSUE THREAD

**Issue by inf3rnus** [slackapi/node-slack-sdk#1488]
Hey all, for the life of me I can't get a modal to open a url directly off of the submit flow... Looking at the docs, I don't see anything suggesting this is possible... Is it that the submit button's only purpose is to initiate a secondary request for handling the callback_id w/ what's provided in the payload? 

Here's a visual just to make sure we're on the same page:

![image](https://user-images.githubusercontent.com/5959983/170143204-149f785f-d861-46ae-a31b-a294ae46010a.png)

If this isn't possible not, I'd like to make a feature request 😄...

Fyi, I know it's possible within the actual blocks, but I want the primary action of a particular modal to take a user to a a website... Stylistically, and UX wise it's kinda weird to have to put a link-out button above the dialog's actions.

**Comment by misscoded** [comment]
Hi @inf3rnus! I did a little digging and can confirm that what you're looking to do does not appear to be currently possible, though I fully understand why you might want to do so. I agree that the UX is less than ideal for the use case you're describing.

The payload you've provided doesn't have any other information filled in, so it's a little hard to tell what the setup is here. That said, is it possible, rather than a modal, to use a message sent to the user to offer up the link-out/sign-in button? Or perhaps send the message after submission? There are a few possibilities here in addition to the one you've identified that might be suitable alternatives.

Anyway, I'm happy to pass on the feedback to the responsible team in the meantime. If you've no other questions, feel free to close this issue, and let us know which solution you end up going with! 🙂
