### ISSUE TITLE
Show or hide message content (a persistent message) for a subset of users

### ISSUE THREAD

**Issue by swarajchavan98** [slackapi/node-slack-sdk#1536]
Description:
When posting a persistent message to a public/private channel, I want to hide a certain text/button block for a user or a certain set of users. Would be great from a user experience point of view to include a "hide" or a "show" property for that text/button block which accepts an array of slack user IDs, thus hiding/showing that particular text/button for those users.

**Example:** 
```
const slackBlocks = {
	"blocks": [
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*Edit this message?*"
			},
			"accessory": {
				"type": "overflow",
				"show": [
					"U00000001"
				],
				"options": [
					{
						"text": {
							"type": "plain_text",
							"text": "*Option1*"
						},
						"value": "value-1"
					}
				],
				"action_id": "overflow-action"
			}
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "_The above overflow menu should only be visible to the user who created this message._"
			}
		}
	]
}
```

E.g.
![image](https://user-images.githubusercontent.com/62349078/192206095-95d504ae-5d9f-4329-8017-84afff0656b0.png)

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @swarajchavan98, thanks for asking the question!

Unfortunately, there is no way to achieve your goal right now and I don't anticipate the Slack platform will be enhanced in that way. The reason is that channel messages need to be consistent for all the channel viewers.

Instead, I would suggest opening a modal view using [views.open API method](https://slack.dev/bolt-js/concepts#creating-modals) and adjust the modal view user interface for each user.

I hope this was helpful to you.

**Comment by swarajchavan98** [comment]
Uh oh. But thanks for your prompt reply!
