### ISSUE TITLE
Get bot-uploaded file Public URL 

### ISSUE THREAD

**Issue by Tievoo** [slackapi/node-slack-sdk#1557]
I've been developing a Slack App for the last weeks and I've run into an issue I couldn't find a way to solve. At the moment, what I'm trying to do is upload a file via `files.upload` with the bot token without specifying any channels, so the file is remaining private. My objective is to send that file in a blocks message, which requires a public URL. For that I thought of using `files.sharedPublicURL`, but this method can only be used with a user token. Is it possible to use this method with a bot token? Or is there a way to generate user token (`xoxp`) for my Bot when I add the app to a workspace?

Thank you in advance.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

Edit: I thought I had selected "question" as the label for the issue, but it seems I didn't. Sorry for that.

**Comment by srajiang** [comment]
👋  @Tievoo! So, to make sure I understand your use-case: 
1. Upload a file and have that file be private (no channel, no thread_ts specified), 
2. At a later point, you want to make that file public and ready to share
3. Then you want to be able to share that file via message / in blocks. 

If that's your use case, then I do recommend getting an xoxp token and using the `files.sharedPublicUrl` method. The reason is because when making a files.upload call if you don't initially specify a channel to share it with, it will default to private only to the uploader (your bot) and there isn't really a way around that either with files.upload or recently released files.uploadV2 (we recommend this since it's a bit more stable btw).

_How to get a xoxp token?_ If your app is a single-workspace one, you can mint an xoxp token straight from the App Config > OAuth and Permissions page for your app (it's easy to do this for development as well). Then in your client.files.upload call, set the option `token` property.

Something like this:
```
    await client.files.sharedPublicURL({
      token: process.ENV.SLACK_USER_TOKEN,
      // other properties here
    })
```

If your app is multi-workspace (meaning you have implemented OAuth), then you'd want your OAuth request to specify xoxp scopes. 

If you're using the [@slack/oauth](https://slack.dev/node-slack-sdk/oauth) package, that's equivalent to setting `userScopes` and I'd point you to the documentation linked for more info on that!

**Comment by Tievoo** [comment]
Thanks for answering. I thought about using the solution provided, but as far as I know, when connecting via OAuth, the user token I receive is from the authed_user which authorized the bot into the workspace. I tried using this token to publicly share the image uploaded by my bot, but the response says `not_allowed`. I assumed this error came from the fact that the user who uploaded the file is my Bot, and the user who is trying to make it public is my Authed User.

**Comment by seratch** [comment]
>I assumed this error came from the fact that the user who uploaded the file is my Bot, and the user who is trying to make it public is my Authed User.

Yes, your understanding here is correct. The file needs to be uploaded by the authed user if you want to make it public (using the authed user's xoxp- token) eventually.

**Comment by Tievoo** [comment]
Which means that I won't be able to make the file public if I make bot to upload it.

**Comment by argonzalez2016** [comment]
Is there a workaround? Why can't the bot make the image public?
