### ISSUE TITLE
How to postMessage with files

### ISSUE THREAD

**Issue by kenshin54** [slackapi/node-slack-sdk#1558]
I'm not sure if this is the best place to post the question about using SDK, please let me know if there is a different place for discussion.

I try to use the web-api to post messages with files, originally I thought it should be process like this,

1. Upload files with `files.upload` API
2. Grab something like fileID and send it as part of the payload of `chat.postMessage`

But it seems the wrong direction. I couldn't find a way to post message with files, I tired to use [File Block](https://api.slack.com/reference/block-kit/blocks#file), but that seems not designed for this purpose, as the doc said, `You can't add this block to app surfaces directly`. 

In the `files.upload` or `files.uploadV2` API, you can upload files with a `initial_comment` field, that one becomes the message text. However you can't use the optional arguments from `chat.postMessage`, we also need `username` and `icon_url` to post message as a different identity.

Since the files we uploaded are images and videos, another option is using Image Block and Video Block. But Video Block has additional issues,

- It requires a `thumbnail_url` aside from `video_url`
- It's rendered slightly different from the file version. And we get the error on iOS when playing video from Video Block, the video is playing, but the App shows an error of "Failed to load video".
![IMG_4900](https://user-images.githubusercontent.com/556914/201678814-40a60537-5540-4636-bd3d-bb45502fd21a.PNG)

Just want to check if I missed something, thanks in advance.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

**Comment by e-zim** [comment]
Hi @kenshin54! Your question is definitely welcomed here, thanks for writing in! Here are a few options for uploading files from a user's identity:

#### With `files.upload`:

If you want to upload and share files under a user's identity, you can use a user token with the `files:write` scope added. To add this scope, navigate to [your app page](https://api.slack.com/apps), then to **OAuth & Permissions**, and add it under the "User Token Scopes" section. This user token can then be used in place of your bot token for the `files.upload` calls you make, making it appear as though a user uploaded the files! An example of uploading and sharing an image in such a fashion follows:

```sh
curl -F file=@code.png -F "initial_comment=check this out\!" -F channels=C0123BCDE -H "Authorization: Bearer xoxp-your-slack-user-token" https://slack.com/api/files.upload
```

#### With `chat.postMessage` and File Blocks:

To use a File Block to display a file instead, your file must be [hosted remotely](https://api.slack.com/messaging/files/remote) (rather than being uploaded to Slack). After adding a remotely hosted file with [the `files.remote.add` method](https://api.slack.com/methods/files.remote.add), you could then use the `external_id` you defined as a field in a File Block while constructing your Block Kit message for `chat.postMessage`!

Hopefully one of these options appeals to you, but feel free to follow up if there's any difficulty with these file uploads!

**Comment by kenshin54** [comment]
@e-zim Thanks for reply and sorry for the wrong label when creating this issue. 

We actually don't need user token(identity), but just using different icon and username for our bot. So the first approrach is not best for us.

For the send approach, I don't know how those external files look like in Slack, but I will try. Thanks for pointing this out.

Also I want to do a check, so the method I described is not viable with the current SDK, right? To be honest, this is the most straightforward path to me, but I don't know why this is not supported. 
 
>Upload files with files.upload API
>Grab something like fileID and send it as part of the payload of chat.postMessage

**Comment by kenshin54** [comment]
@e-zim Also, do you know what caused the "Failed to load video" error?

**Comment by e-zim** [comment]
No worries with the labels! And the method you're describing does not seem straight forward due to [the visibility of files](https://api.slack.com/methods/files.upload#markdown) uploaded with `files.upload`:

> By default all newly-uploaded files are private and only visible to the owner. They become public once they are shared into a public channel (which can happen at upload time via the `channels` argument).

Meaning the `files.upload` call would be posting the file as the uploading bot. This response does provide a permalink that you can share in later calls to `chat.postMessage` (with username and icon customization), but this permalink only works if the file is shared to a channel in the `files.upload` call, which might create an odd experience.

**Comment by e-zim** [comment]
I'm also not immediately sure why the "Failed to load video" error is appearing.. There could be an HTTP error occurring when loading the video, or there might be a problem with the `video_url`. Does the URL you are using show the same file you're expecting? You may also have to [register your domain](https://api.slack.com/reference/messaging/link-unfurling#configuring_domains) for it to be properly unfurled. And is the "View in browser" button directing you to the correct video or is it slightly different than what you're expecting?

**Comment by seratch** [comment]
As for the video loading issue, there are a few requirements -- 1) the video URL must be publicly accessible, 2) the domain must be registered (as @e-zim mentioned), 3) the URL must return only the video content. 

Please refer to the following resources for more details:
* https://api.slack.com/reference/block-kit/blocks#video
* https://github.com/slackapi/java-slack-sdk/blob/d537d731c16f8695952befe486aa3a19f3c34dd5/slack-api-client/src/test/java/test_with_remote_apis/methods/chat_Test.java#L986

**Comment by kenshin54** [comment]
@e-zim @seratch Thanks for the response. After trying a few options, we landed on this approach. 

Still using `Image Block` and `Video Block` for presenting the media content, this allows us being able to use `postMessage` API and the customized bot photo and name. Regarding the video error, I think we did meet those three requirements, but still get the error. Alternatively, The Youtube video inspired me an alternative solution, we build a web page with a video player rather than the raw video url, now the error is gone. I still feel this is probably a bug on Slack, because that error is only raised on the mobile version, but not desktop Slack client.

The only remaining "non ideal" problem is that the video preview is not as good as the uploaded one. I think only uploaded video has those metadata such as width/height/duration, so it can be rendered better. It's okay for us considering the other capabilities we need. 

Thanks again for the feedbacks, I'm going to close this issue.
