### ISSUE TITLE
Add `req` argument to installation store methods

### ISSUE THREAD

**Issue by ianberdin** [slackapi/node-slack-sdk#1565]
We have multi workspace application.

Can you please add `req` argument to installation store methods, because our app requires to get current user token from cookies.

For an example:
```js
const installationStore = {
  storeInstallation: async (installation, req) => {
    const user = getUserByToken(req.cookies.accessToken);
    
    db.createInstallation({..., userId: user.id})
  },
  
  fetchInstallation: async (installQuery, req) => {
    const user = getUserByToken(req.cookies.accessToken);
  
    db.getInstallation({..., userId: user.id})
  },
  deleteInstallation: async (installQuery, req) => {
    const user = getUserByToken(req.cookies.accessToken);
  
    db.deleteInstallation({..., userId: user.id})
  }
}
```

#### Packages:

Select all that apply:
- [*] `@slack/oauth`

**Comment by srajiang** [comment]
👋 Hi @ianberdin!  I'm assuming that your app intends to follow the modern V2 Oauth 2.0 request [flow](https://api.slack.com/authentication/oauth-v2#overview). I don't see a scenario where the a granular access token would be set on request cookies by Slack. 

To take your example, if properly authorized, by the time that the `storeInstallation` callback is evoked, the `installation` provided to your handler should contain a token, because Bolt takes care of calling the [oauth.v2.access](https://api.slack.com/methods/oauth.v2.access) endpoint and builds the `installation` based on the [response](https://api.slack.com/methods/oauth.v2.access#response) for you. 

Could you please elaborate on your intended use case here?

**Comment by ianberdin** [comment]
Thank you for quick response!

We have this use cases:
1. Authorized user in our website click to `Add to Slack` button. It call storeInstallation() handler. We want to get the user from request by Our token stored in cookies and attach Slack Installation to his account.

2. User A added app to slack.
2.1 User B added same app to slack. Yes, he can't, because User A already added it, so we just store slack installation again with userId. User A and User B don't have common permissions in our website, so User A can "remove" app, but User B will continue to use it (we just remove it our from database).
The problem is: we need to pair of slack.team.id and Our user.id to get Right installation in handlers.

**Comment by srajiang** [comment]
Would the `beforeInstallation` callback be helpful for this use case then? It's a callback you implement and supply as `callbackOptions` and it accepts the full `req` object as args.

More on that in the Persisting data during the Oauth Flow section here: https://slack.dev/node-slack-sdk/oauth
