### ISSUE TITLE
ClientOptions.maxRequestConcurrency default value and types

### ISSUE THREAD

**Issue by callumsteele4** [slackapi/node-slack-sdk#1582]
### Description

I've been debugging a Slack app I've built that is showing slow performance only when it is utilised in large channels. The underlying cause looks to be due to the number of requests I make to the Slack API via the `WebClient` in a burst. Initially I thought this might be due to rate limiting, but then I noticed that the `WebClient` instance utilised in this library defaults to a max concurrency of 3, and that the types do not make clear that modifying this value is possible nor whether it will be supported going forward.

I can't find any discussion of this value in any prior issues or pull requests so I wanted to ask if there is a specific rationale behind using this value instead of using the default `Number.POSITIVE_INFINITY` from `WebClient` + `p-queue` (that is used under the hood).

It would seem that the Slack API's rate limiting should already solve for any concerns around request load.

Please let me know if a pull request to increase the default or to expose this option from `WebClient`'s types would be welcomed.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/bolt/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@callumsteele4 Thanks again for bringing this!

Keeping the default value small enough to detect potential issues early in development is a common practice for libraries. However, setting 3 concurrency for WebClient looks a bit too conservative considering general Slack API use cases.

Thus, I agree that we can revisit this default value. Meanwhile, I hesitate to change the value to infinity as it may cause unexpected behaviors in some situations (especially when an app does not have any great resource observability for its server instances). I think that we can consider 100 as the new default value as it should work for most situations. If developers who work on extremely busy apps (like you!) need more concurrency, they can adjust the options to be optimal to their apps.

If you can agree on above, we're happy to accept your pull request for it. Otherwise, our team will make the change and cut a new version when we have the bandwidth for it.

**Comment by callumsteele4** [comment]
> Hi @callumsteele4, thanks for taking the time to report this! Since the default value (3) is set on the node-slack-side, let me transfer this issue to the repo before starting the discussion https://github.com/slackapi/node-slack-sdk/blob/%40slack/web-api%406.8.0/packages/web-api/src/WebClient.ts#L166

Ah apologies on this @seratch, I must have misread where this was being set by default!

I'll have a go at putting together a pull request for this, thanks for being open to the change.

**Comment by callumsteele4** [comment]
I've added a pull request [here](https://github.com/slackapi/node-slack-sdk/pull/1583).

I do wonder if it is also worth making an update in the `slackapi/bolt.js` library however to expose the types / documentation / etc that make it clear that `maxRequestConcurrency` is modifiable via config?
