### ISSUE TITLE
conversations.invite method does not invite valid users when an invalid user ID is provided

### ISSUE THREAD

**Issue by arunkasireddi** [slackapi/node-slack-sdk#1596]
When using the `conversations.invite` method with a list of Slack user IDs does not invite the valid users. I received a partially failed response but the valid users does not get invited to the channel. 

We are trying to invite a list of users to a slack channel. (comma separated). 

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

"slack/web-api": "^6.8.1",
"passport-slack-oauth2": "^1.1.1",

#### Node.js runtime version

v16.13.0

#### OS info

ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68
Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64

#### Steps to reproduce:
In the code: 
```
await this.slackWebClient.conversations.invite(args)
```

args: 
```
{
  "channel": "C0XXXXXXXX",
  "users": "U0XXXXXX1,U0XXXXXX2"
}
```

CURL command (produces same behaviour).
```
curl --location 'https://slack.com/api/conversations.invite' \
--header 'Authorization: Bearer xoxb-' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'channel=C0XXXXXXXX' \
--data-urlencode 'users=U0XXXXXX1,U0XXXXXX2'
```

### Expected result:
1. User with ID `U0XXXXXX1` should be invited to the channel. 
2. User with ID `U0XXXXXX2` should fail. 

### Actual result:
As mentioned in the documentation here: [conversation.invite](https://api.slack.com/methods/conversations.invite), I was expecting a partially failed response.
The valid user is not invited. I received the below response from the API. 

```{
    "ok": false,
    "error": "user_not_found",
    "errors": [
        {
            "user": "U0XXXXXX2",
            "ok": false,
            "error": "user_not_found"
        }
    ]
}

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @arunkasireddi 👋🏻  Thanks for sharing this issue!

I agree, it would be a better developer experience for the API to invite the valid users before returning an error for the invalid users.

Since this is a server-side Slack API issue, I've shared it with the Slack API team. We have no control over when it will be resolved, but I've linked them to this issue for more detail. If others are experiencing this problem, I'd recommend throwing a 👍🏻 on the issue to show your support!

@arunkasireddi Have you noticed whether some users are invited before the failure? Or, is the Slack API validating that all users exist before starting to invite them?

**Comment by arunkasireddi** [comment]
Hi @mwbrooks Thanks for your response. 

When there is a failure none of the users in the request are invited. It is either all or nothing. 
Slack API validates all users before inviting them.

**Comment by mwbrooks** [comment]
@arunkasireddi Thanks a bunch!

At least it's all-or-nothing, which makes it easier to resolve. In your code, you may want to capture the error and remove the users not found before retrying. That way you can continue to use a single API call to invite a bulk number of users (rather than making a bunch of individual API calls).

**Comment by arunkasireddi** [comment]
Thanks @mwbrooks. We have implemented this as a workaround for now. 🤝

**Comment by mwbrooks** [comment]
So quick @arunkasireddi, congrats!
