### ISSUE TITLE
conversations.kick should accept multiple ids

### ISSUE THREAD

**Issue by ofmycwt** [slackapi/node-slack-sdk#1600]
(Describe your issue and goal here) 

#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

### Requirements

Just like `conversations.invite` accepts a comma-separated list of user IDs, I think `conversations.kick` should do the same to kick multiple users in a single API call.

**Comment by e-zim** [comment]
Hi @ofmycwt 👋  Thanks for this suggestion! I agree that having `conversations.kick` accept multiple user IDs would be convenient as it would match the behavior of `conversations.invite`.

Since the SDK is directly calling this endpoint, this change requires updates to the `conversations.invite` method and is not something that can be addressed directly by the SDK. For now, I will bring this request to the team that maintains this method and will let you know if there are plans to introduce this change!

**Comment by e-zim** [comment]
I checked with the team and there are unfortunately no current plans for making this change. However, we'll keep track of this feedback and share any related updates going forward. Until then, I will close this issue, but feel free to reach back out if you have any other thoughts, troubles, or questions!

And as a workaround to this issue, I would suggest making individual calls to the `conversations.kick` method for each `user_id`. This method has [a Tier 3 Rate Limit](https://api.slack.com/docs/rate-limits#tier_t3) which can hopefully support the occasional large burst of activity, but please let us know if you're running into a `ratelimited` error regularly!
