### ISSUE TITLE
can't use @slack/web-api in vercel edge functions: The edge runtime does not support Node.js 'path' module.

### ISSUE THREAD

**Issue by GorvGoyl** [slackapi/node-slack-sdk#1603]
Request devs to add support for @slack/web-api in [Vercel edge functions](https://vercel.com/docs/concepts/functions/edge-functions).

Currently, I see this error when trying to use: `The edge runtime does not support Node.js 'path' module.`

#### Packages:

Select all that apply:

- [x] `@slack/web-api`

**Comment by hello-ashleyintech** [comment]
Hi, @GorvGoyl! Thanks for submitting this question!

While I'm unsure about current `@slack/web-api` compatibility with Vercel edge functions, based on the error you submitted, it looks like the error is being returned on the Vercel side. The error `The edge runtime does not support Node.js 'path' module` looks like it is because [the Edge runtime does not support certain Node.js-specific modules](https://github.com/vercel/next.js/issues/43115#issuecomment-1321785193), since it aims to be a minimal portable runtime. I am unsure of a workaround currently since 'path' is used in the `@slack/web-api` package as part of the core functionality of the package.

If your use case is generally just aiming to use Vercel with Slack, you might find [this issue](https://github.com/vercel/vercel/discussions/6039) helpful as a starting point to build Vercel with our Bolt framework as well as [this example](https://github.com/vercel/examples/tree/main/solutions/slackbot) of a Slackbot with Vercel.

I hope this helps!

**Comment by ValentinH** [comment]
Up

**Comment by seratch** [comment]
Hey @ValentinH, thank you for your interest! Unfortunately, our SDK team does not have short-term plans to make any changes to the Node SDK to make it available for any edge function runtimes, due to priorities and team capacity.

However, I recently explored a better way to build Slack apps on Vercel Edge Functions / Cloudflare Workers and started my personal projects for it:
* https://github.com/seratch/slack-web-api-client
* https://github.com/seratch/slack-edge

These libraries offer a better developer experience with TypeScript, in addition to stable edge function compatibility. I understand you may prefer to use the official SDKs as much as possible, but if you're open to these 3rd party ones, please try them out.

**Comment by ValentinH** [comment]
Hey @seratch ,  this is great news and as we are already used to live on the edge, using a non- official client is not an issue! 😅

**Comment by papaya-reader** [comment]
@seratch thanks for the sdk. there's an issue with CORS when using it in the browser mentioned here https://github.com/slackapi/node-slack-sdk/issues/1568. I tried its suggested workaround by patching your sdk and it works. would you support the CORS in this sdk? I simply commented out this like https://github.com/seratch/slack-web-api-client/blob/main/src/client/api-client.ts#L466

**Comment by seratch** [comment]
@papaya-reader Thanks for trying the library out! Generally speaking, I don't advise exposing a Slack OAuth token to any JavaScript code in a web browser. In certain cases, doing so in an Electron app etc. might be safe enough (perhaps, you are doing this). Despite such possible use cases, I'm still reluctant to enable it for developers in my library, as those at a beginner level may do so without considering the potential security implications. 

If you'd like to further discuss this, could you create a discussion issue on my library side? As this is an issue tracker for Slack's official SDKs subscribed to by many people, I'd prefer to avoid unnecessary noise for them.

**Comment by filmaj** [comment]
The main usage of `path` in `@slack/web-api` is to enable file uploading capabilities and allowing developers to provide a file path for uploading files to Slack. This is a core feature and will not be going away. As such, I think we can close this issue as "won't do". Furthermore, this SDK is explicitly targeted at supporting the node runtime, so asking for support for a different runtime is out of scope from the official Slack package.

That said, the only method used from `path` within this program is `basename`, which is nothing more than a simple path/string manipulation operation:

```
➜ ack basename src
src/instrument.ts
2:import { basename } from 'path';
21:                      `${basename(process.title)}/${process.version.replace('v', '')} ` +

src/WebClient.ts
3:import { basename } from 'path';
648:                return basename(streamOrBuffer.name);
651:                return basename(streamOrBuffer.path);
```

If anyone here is passionate about this particular issue and adding support for it, I would suggest exploring replacing `path.basename` with a different implementation in order to remove the dependency on `node:path`. Assuming file uploading capabilities are still honoured and functioning, I think we would accept any such contributions.
