### ISSUE TITLE
User lookup by name/nickname

### ISSUE THREAD

**Issue by andreasvirkus** [slackapi/node-slack-sdk#1610]
I'm trying to create a Slack user(s) search in my app so the user could create their own custom group of users (imagine setting up a game between `N` users in your Slack). I was really surprised to see that the only possible lookup method is by email and nothing equivalent for the name/nickname 🤔 Is the only option really to paginate through the full list of users so I could perform a lookup on the full result set then? 

Related to https://github.com/slackapi/node-slack-sdk/issues/73#issuecomment-497127404, I think

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

(Paste the output of 
```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
```
or refer to your `package.json`)

#### Node.js runtime version

(Paste the output of `node --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
What about creating a [modal](https://api.slack.com/surfaces/modals) that includes a [multi-select menu interactive component](https://api.slack.com/reference/block-kit/block-elements#multi_select) (and specifically [the multi-select menu of users](https://api.slack.com/reference/block-kit/block-elements#users_multi_select))? This is an easy and intuitive interface for users, and the select menu interactive component handles searching for users and limiting the users to just the users in the current workspace?

**Comment by andreasvirkus** [comment]
Hi, the interface isn't inside Slack but rather a web app where the user has logged in via Slack + integrated with their Slack org via oauth ("Add to Slack"). This is what I'd love to achieve: display a certain amount of users by default (for example 20) and load the rest based on the user's search query

<img width="567" alt="Screenshot 2023-04-20 at 22 21 11" src="https://user-images.githubusercontent.com/9140811/233466583-3bc02286-1239-425e-8d56-9bb147cacf56.png">

**Comment by filmaj** [comment]
Ah yes with the system being outside of Slack this becomes more complicated :(

This issue https://github.com/slackapi/node-slack-sdk/issues/1345 discusses someone maintaining a cache of users in their own external system in order to query as they desire. Perhaps that is a solution for you. Perhaps doing something like a one-time export of all the users using the `users.list` API, and then maintaining the cache by subscribing to the [`team_join` event](https://api.slack.com/events/team_join) to be informed when a new user joins, and the [`user_change` event](https://api.slack.com/events/user_change), and specifically the `deleted` field inside here, to know when a user has left.

**Comment by andreasvirkus** [comment]
Thanks. Would it be possible to add a feature request for a new lookup endpoint as well? We'll continue with the current `users.list` endpoint for now with a cache on our side 🖖

**Comment by filmaj** [comment]
I will raise this internally for sure 👍

**Comment by KamikazeWombat** [comment]
I too would like to request a way to lookup userid based on the @username text.  I have an external app with a text box that people can put a list of people to ping for alert messages, pings work sometimes and don't sometimes.  It appears they only work if the person's current @username is their actual original username, not their current name.  The cached list thing may be a workaround but we have 1700 users and I really don't want to do that.  Seems like there has to be a better way to find the userid based on current display name than to search a list of all users for it.

**Comment by davidgs** [comment]
I need this as well. I have built a SlackApp to add folks to a management team (and a private channel) but with ~4k members, the `user_select` doesn't work because it's limited to 100 names. I'd like to have a drop-down that is an `external_select` with `min_query_length=4` and then do a search, but that doesn't work, since I'm limited to < 1000 names per `users.list()` call, and even then, it's not a search. `users.search({id: userId, username: name, full_name: name}) where only one of those fields -- as a partial -- would do the search is what I'm looking for.
