### ISSUE TITLE
[CI] Is it possible to generate an app configuration token programmatically?

### ISSUE THREAD

**Issue by callumsteele4** [slackapi/node-slack-sdk#1622]
I'm looking to automate the deployment of a Slack app to multiple environments. It looks like utilising a yaml file for the manifest will help to ensure that they remain in-sync.

The update manifest endpoint (https://api.slack.com/methods/apps.manifest.update) looks ideal for pushing the manifest file to a specific app to achieve this, but I'm drawing a blank as to how I can generate the app configuration token programmatically.

Is this something that is currently supported? Or is it expected that an app configuration token should be manually generated prior to each deployment?

**Comment by mwbrooks** [comment]
Hey @callumsteele4 👋🏻 

Great topic! A few of us have been discussing this same topic inside Slack and started investigating into whether we can offer such a token for developers to use in a CI/CD environment.

I think your idea of using the `apps.manifest.update` method to update the manifest file for a collection of apps is a good approach. You can also use JSON instead of YAML if that's more comfortable for you.

Today, there is no public way to programmatically generate a long-lived token, but I can make a suggestion on how you could approach it:

1. Generate an [App Configuration Token](https://api.slack.com/authentication/config-tokens#creating)
2. Store the **App Configuration Token** as an environment variable in your CI/CD
3. Store the **App Configuration Refresh Token** as an environment variable in your CI/CD
4. When your Token expires, [refresh it with the `tooling.tokens.rotate` method](https://api.slack.com/authentication/config-tokens#rotating)
    - Update the environment variable in your CI/CD with the new App Configuration Token and Refresh Token
    - If you're using GitHub Workflows, you can [update a repository environment variable](https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28#update-a-repository-variable) or [org environment variable](https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28#update-an-organization-variable) using the GitHub API

I know it's a little complicated, but I hope that helps you out!

If possible, I'd love to know what CI/CD you're using 🙂

**Comment by callumsteele4** [comment]
Oh! I completely missed that the refresh token has no expiry, that will work perfectly - thanks!

CI/CD - currently nothing, but I'll be setting up GitHub actions shortly, so your choice of example is perfect 👌 

Cheers for the prompt reply @mwbrooks 👍
