### ISSUE TITLE
Support for Datastores in Node

### ISSUE THREAD

**Issue by garviand** [slackapi/node-slack-sdk#1630]
Hi! I am interested in using the Slack-hosted datastores for caching data about our users' state: https://api.slack.com/automation/datastores

It looks like support has been added to the https://github.com/slackapi/deno-slack-sdk SDK. Are there plans to add support to the node Web API package?

I'll admit I am a little unclear about the intended use of the datastores, so this may not be relevant, but they do seem to fit my needs!

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

**Comment by zimeg** [comment]
Hey @garviand 👋 Really appreciate the question, but unfortunately there are no immediate plans to support datastores outside of the Deno SDK.

Storing state and caching data certainly seems like an ideal use case for these but with the Node SDK this would require using your own database at this time – perhaps something self-contained like SQLite.

I know this might not be ideal, but I hope this isn't a blocker for you. This is also really great feedback to receive as it helps us prioritize future features, so I will be sure to share this with the team!

For now though let's close this issue since there aren't any immediate next steps, but please feel free to follow up with any other questions!
