### ISSUE TITLE
How to add clear selection in date picker block  ?

### ISSUE THREAD

**Issue by chintan-scaletech** [slackapi/node-slack-sdk#1631]
I want clear selection block in date picker like this pic

![image](https://github.com/slackapi/node-slack-sdk/assets/116252348/1a6875d1-fae3-42d7-877b-520cad7abbf4)

**Comment by seratch** [comment]
Hi @chintan-scaletech, could you elaborate more on your question here? As you can see, "Clear selection" exists when a user clicks a date picker element. That's the only UI that Slack offers.

**Comment by chintan-scaletech** [comment]
I want clear selection block in date picker like above pic

**Comment by seratch** [comment]
@chintan-scaletech Thank you very much for being patient here. I have also confirmed that the "clear selection" part is not available in the UI for some reason. The UI in Block Kit Builder and the actual one in Slack client apps should be consistent.

I apologize for bothering you again, but would you mind sharing this feedback directly with your customer support team? Since this is an issue tracker dedicated to our Node.js SDK issues, the only thing I can do for you is to escalate the issue on your behalf. Communicating through the customer support channel should be smoother and faster in getting a response. You can submit an inquiry via either `/feedback` in your Slack workspace or at https://my.slack.com/help/requests/new. It would be greatly appreciated if you could understand this.
