### ISSUE TITLE
Is there a Slack equivalent to GitHub's personal access tokens?

### ISSUE THREAD

**Issue by richard-ling** [slackapi/node-slack-sdk#1634]
The [README](https://github.com/slackapi/node-slack-sdk#getting-help) advises using issue tracker to ask questions, so here goes 😆

When logged into GitHub, I can easily generate a ["personal access token"](https://github.com/settings/tokens) which lets me call the GitHub API to automate basically all the same things I can already do manually with the web app.

Q1: When logged into Slack, can I create an equivalent Slack token which will let me call the Web API with the same permissions as I already have in the Slack desktop app?

In anticipation that the answer is "no, there is no such thing", please let me pre-emptively ask my second question...

Q2: _Why_ is this use case not supported?

I'm genuinely interested.  I can imagine it just being a low priority, but can equally imagine that it's a deliberate omission from the product roadmap, or that nobody in-house is aware the use case exists, or that there's too strong focus on enterprise-class apps, or some other unguessable reason.  Help me out here -- thanks!

**Comment by seratch** [comment]
Hi, @richard-ling thanks for writing in!

As you guessed, the answer to Q1 is "no". The token used by Slack client apps (Desktop, web browser, etc.) is not available for 3rd party apps.

As for Q2, it's intentionally unsupported. Enabling 3rd party app developers to perform all the actions that the 1st party client app can do would require a huge amount of effort. Unfortunately, this is an undertaking we can't handle at this time. So, I'm sorry to say, I don't anticipate that Slack's platform team will make substantial investments in this area in the future.

I understand that this might not be the answer you were hoping for, but I hope it clarifies the reasoning behind our policies.

**Comment by richard-ling** [comment]
Ahh cool, well thanks for answering anyway.

As for Q2, I'm a bit confused by your answer - may I ask some follow-up questions?

When you say "it's intentionally unsupported" and "it would require a huge amount of effort", to me these are opposing (contradictory) reasons. I think "intentionally unsupported" means we would not support it even given unlimited resources, because we have some other reason (e.g. a business reason) to not want users to do this.  And I think "it would require a huge amount of effort" means we would like to support it but we can't allocate resources because it's a lower priority than other tasks.  Am I right?  Can you clarify which is the most correct reason?

If it's ONLY because "enabling 3rd party app developers to perform all the actions that the 1st party client app can do would require a huge amount of effort" , hopefully you know that I'm not asking for that - the existing API looks perfectly adequate - all that is needed is for a logged-in user to be able to create a [user token](https://api.slack.com/authentication/token-types#user) for their own user account.  As a dev, this doesn't seem like it would be a huge amount of effort, however I'm certainly not rude enough to assume that I know as much about Slack's products or practices as Slack's own devs do.

If it's "intentionally unsupported" (how I define it above), I'd like to know why, because I can think of many cases where it would be very useful. For example, a vision-impaired user could pipe her unread messages through text-to-speech; a deaf user could add notifications through other channels such as a flashing light or vibration; users with certain other disabilities (and many without!) could benefit from more flexibility around how notifications are filtered or delivered; I would like a more capable search than the client's built-in one, a task which grep is perfectly suited to, and I'd like to run it automatically rather than always going back through the desktop client's GUI.  Surely Slack doesn't seek to make such use cases "intentionally unsupported" (i.e. to actively block them), which is why I'm interested in finding out the real situation.

**Comment by seratch** [comment]
Hi, thank you for your follow-up questions. Indeed, my response may not have been detailed enough.

>nobody in-house is aware the use case exists

The main reason why I used the phrase "intentionally unsupported" was specifically to address this point. We are aware of such use cases, but as per the current platform design, we decided not to support it and instead encourage developers to configure "apps". This enables Slack workspace/org admins to better manage the integrations available in their workspaces/orgs. While it may be technically possible to add some support for individual-level token management, doing so would require careful consideration of security models and significant design/engineering resources (which I referred to as "huge efforts" from the entire organization). Also, from a business perspective, we have other priorities to focus on.

As for your search use case and accessibility ideas, we appreciate you sharing them! As you may know, Slack has been consistently improving in these areas and we will continue to do so. I understand that you'd like more control, but our primary approach will be to provide the best experience through our first-party Slack client apps.

Since this is an issue tracker for our developer SDK tools, we don't have anything further to share on the product roadmap. Therefore, I will close this issue now. If you have more details to share with our product team, please contact our customer support team instead (you can send an inquiry via either /feedback in your Slack workspace or https://my.slack.com/help/requests/new). I would appreciate it if you could understand this.

Thanks again for writing in, and I hope my responses were helpful to clarify the things.

**Comment by richard-ling** [comment]
Thank you!  As a customer, I can't say I fully agree with these decisions, but I do appreciate you taking the time to give a more detailed answer.  I'll live in hope that other approaches to these use cases may be supported in future.
