### ISSUE TITLE
Can we get an accurate timestamp (with numbers after the decimal point) from a scheduled message?

### ISSUE THREAD

**Issue by vikramnayyarcs** [slackapi/node-slack-sdk#1645]
We're trying to get the timestamp from a scheduled message and use it to update the scheduled message **once** it's posted. 

When we get the timestamp from the scheduled message, it doesn't have enough accuracy (nothing after .) and we can't set it with enough accuracy (padding with 0's: .000000) for it to be considered an actual timestamp because it needs to have that extra detail.

It appears that there's no way to find the right timestamp for a message that has been scheduled.

In regards to the following functions:

client.chat.schedulemessage.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [x] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

(Paste the output of 
```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
```
or refer to your `package.json`)

#### Node.js runtime version

(Paste the output of `node --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by WilliamBergamin** [comment]
Hi @vikramnayyarcs thanks for writing in 💯 

You are correct the `timestamp` returned by `chat.schedulemessage` isn't the actual `timestamp` associated with the `message` since the message does not yet exist.

A potential work around to update the scheduled message once it is posted 
1. Make a request to [`conversations.history`](https://api.slack.com/methods/conversations.history) with the `latest` and `oldest` parameter populated with values that closely isolate the `post_at` field returned from `chat.schedulemessage`. This will recover the actual message data and its real `timestamp`.
2. Once the real `timestamp` is recovered you should be able to use [`chat.update`](https://api.slack.com/methods/chat.update) as usual

let me know if this fixes your issue 🗺️

**Comment by vikramnayyarcs** [comment]
> Hi @vikramnayyarcs thanks for writing in 💯
> 
> You are correct the `timestamp` returned by `chat.schedulemessage` isn't the actual `timestamp` associated with the `message` since the message does not yet exist.
> 
> A potential work around to update the scheduled message once it is posted
> 
> 1. Make a request to [`conversations.history`](https://api.slack.com/methods/conversations.history) with the `latest` and `oldest` parameter populated with values that closely isolate the `post_at` field returned from `chat.schedulemessage`. This will recover the actual message data and its real `timestamp`.
> 2. Once the real `timestamp` is recovered you should be able to use [`chat.update`](https://api.slack.com/methods/chat.update) as usual
> 
> let me know if this fixes your issue 🗺️

We found a different solution (using node-cron) that worked for our use case (scheduling messages once a week, once a month ...).
