### ISSUE TITLE
Socket mode stop responding to messages from slack after some time 

### ISSUE THREAD

**Issue by razbikel** [slackapi/node-slack-sdk#1652]
#### Packages:

- [X] `@slack/socket-mode`

#### The Slack SDK version

"slack/socket-mode": "^1.2.0",
"slack/web-api": "^6.5.0",

#### Node.js runtime version

v17.3.0

#### OS info

app executed on docker container on alpine linux

#### Steps to reproduce:

I'm using Nest JS framework as a web server in Typescript and creating a socket mode client instance with the following code when the app init:

            this.socketModeClient = new SocketModeClient({
                appToken: this.appToken,
                autoReconnectEnabled: true,
            });
            
           I use slack app to send messages to my server.
            
            

### Expected result:

a web socket connection that will always be connected, and will reconnect automatically if required.

### Actual result:

After some time (few days) the socket mode connection stop responding to messages from slack. This issue is fixed when the docker container restarts (but it is not a proper solution).
I already tried  the following:
1. Using  the "disconnect" property of the socketModeClient to understand if the bot is disconnected (and then reconnecting it) but for some reason is still contains "true" even when the server not responding
2. Listen to "disconnected" event, and when catching it use the "start" function to start the connection again - however what the happened is that I got the following error: 
"Unhandled event 'explicit disconnect' in state 'disconnecting"

**Comment by seratch** [comment]
Hi @razbikel, thank you for reaching out.

You might have noticed that `SocketModeClient` has an internal mechanism to monitor the liveness of its underlying WebSocket connection. If the connection becomes inactive due to issues like network instability, the client automatically tries to re-establish a new connection. Normally, this should work smoothly, but in your case, external factors might be preventing stable auto-reconnection. You have two options to address this:

1. Implement a custom health-check endpoint within your main web app. This endpoint could use the `isActive()` method to assess the connection's status. If `isActive()` returns false, you can terminate the problematic instance.
  
2. Alternatively, if you want to avoid having a health-check endpoint like above, you can have a periodical job that validates the liveness. When `isActive()` returns false within the code, your app can dynamically re-create the `SocketModeClient` instance.

I hope this helps.

**Comment by razbikel** [comment]
Hi @seratch
Thank you for your response.
I dont see that the SocketModeClient has an isActive method, maybe its related to the package version (currently I use @slack/socket-mode": "^1.2.0) ? Maybe upgrading the package would help?
I tried to use the "connected" property but it contains value of "true" even when the SocketModeClient stop responding to slack messages.
For now I'm trying to execute a scheduled job that disconnect the bot with disconnect() method, and then reconnect it with start() method. Not the best solution but you think it might help with my situation?

**Comment by seratch** [comment]
@razbikel We've applied a bunch of improvements. Please upgrade to the latest version. Your issue may be resolved just by uprading the version: https://github.com/slackapi/node-slack-sdk/releases?q=%22socket-mode%22&expanded=true
