### ISSUE TITLE
Mrkdwn - Single word formatting with combinations

### ISSUE THREAD

**Issue by GitFlowin** [slackapi/node-slack-sdk#1698]
Hello,

I am curious on the expected behavior of the `mrkdwn` block formatting, specifically single words that combine formats.

When using the block below:
```
{
    "blocks": [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "_italic_*bold*~strike~\n*bold*_italic_~strike~\n~strike~*bold*_italic_"
            }
        }
    ]
}
```

The formatting is inconsistent, where the first line's italic is formatted, but **all** others are not _until_ you had a space between the mrkdwn syntax.

You can see an example on [Slack's Block Kit Editor](https://app.slack.com/block-kit-builder/T5FPG1QQ0#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22_italic_*bold*~strike~%5Cn*bold*_italic_~strike~%5Cn~strike~*bold*_italic_%22%7D%7D%5D%7D)

Does Slack's block not support single word combination formatting? Or is this a bug with Slack's mrkdwn formatting?

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

latest

#### Node.js runtime version

latest

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

See description

### Expected result:

See description

### Actual result:

See description

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by zimeg** [comment]
Hey @GitFlowin 👋 Thanks for sharing the example! This seems like an edge case and I'll check if this is expected behavior or not.

For now, it might be possible to use the [`rich_text_input`](https://api.slack.com/reference/block-kit/blocks#rich_text) block to achieve the formatting you're hoping for. Here's [the same example](https://app.slack.com/block-kit-builder/T5J4Q04QG#%7B%22blocks%22:%5B%7B%22type%22:%22rich_text%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22italic%22,%22style%22:%7B%22italic%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22bold%22,%22style%22:%7B%22bold%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22strike%5Cn%22,%22style%22:%7B%22strike%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22bold%22,%22style%22:%7B%22bold%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22italic%22,%22style%22:%7B%22italic%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22strike%5Cn%22,%22style%22:%7B%22strike%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22strike%22,%22style%22:%7B%22strike%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22bold%22,%22style%22:%7B%22bold%22:true%7D%7D,%7B%22type%22:%22text%22,%22text%22:%22italic%22,%22style%22:%7B%22italic%22:true%7D%7D%5D%7D%5D%7D%5D%7D) using these blocks!

If you're curious, this is actually what's actually shown from the current `mrkdwn`. Courtesy of [Slack Developer Tools](https://sdt.builtbyslack.com/):

![blocks](https://github.com/slackapi/node-slack-sdk/assets/18134219/967ace5f-b19b-4bdb-a883-b20e677c9155)

**Comment by GitFlowin** [comment]
Hi @zimeg, thank you for the quick response and appreciate you looking into this edge case. I will look at using the alternative block, although it may require a large refactor on my part, seems like there is a path forward.

Very interesting, so it seems the `mrkdwn` ultimately gets translated into a `rich_text` block somewhere down the line, I will keep an eye out for the expected behavior, thank you!

**Comment by GitFlowin** [comment]
Understood, we will look into the recommended `rich_text` block option, as it seems to be the safer alternative vs. the zero-width space option 😉 (but indeed clever)

Appreciate your help!
