### ISSUE TITLE
channel_not_found with files.upload v2

### ISSUE THREAD

**Issue by noisypants** [slackapi/node-slack-sdk#1701]
(Filling out the following with as much detail as you can provide will help us solve your issue sooner.)

#### Packages:

Select all that apply:

- [X ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

```
"slack/bolt": "^3.13.3",
"slack/web-api": "^6.9.0"
```

#### Node.js runtime version

v18.16.0

#### OS info
WSL2

#### Steps to reproduce:

If `fileRef.content` is a `Stream`, the file will fail to upload.
```
			const response = await this.webClient.files.uploadV2({
				channel_id: channelId,
				title: filename,
				initial_comment: message,
				file: fileRef.content,
				filename: filename
			});
```

### Expected result:

The spec for the `file` parameter says: 
```
file?: Buffer | Stream | string;
```
`Stream` works for `files.upload`, but we receive the warnings that `files.uploadV2` is recommended.  When I tried it, it fails due to that code path seemingly not supporting `Stream`s?

### Actual result:

Get a post in the channel with a failed file: 
![image](https://github.com/slackapi/node-slack-sdk/assets/1570161/ddfad061-5a4e-417a-ab9f-4a43ecb67a43)

**Comment by seratch** [comment]
Hi @noisypants, thanks for asking the question. The "channel_not_found" error indicates the channel ID you've passed was not accesible with the token you used for the API call. I guess you're using a channel name instead of channel ID. If yes, the v2 method does not support a channel name parameter (for context: only long-lived APIs such as chat.postMessage, files.upload etc. support both ID and name; newer APIs do not support name anymore). Please pass a channel ID instead.

**Comment by noisypants** [comment]
Thanks for the response @seratch .  I will give this a shot and see.

**Comment by noisypants** [comment]
Confirmed!  channelid vs channel name was the issue!  thanks.
