### ISSUE TITLE
Update files.upload Documentation on Slack API Website for files.uploadV2

### ISSUE THREAD

**Issue by OODemi52** [slackapi/node-slack-sdk#1756]
I'm not entirely sure if this is the right place to make this issue, but when looking into documentation about the `files.upload`, the website only has relevant information for the original `files.upload` method and not the `files.uploadV2` method. Since it seems Slack is encouraging developers to use the `file.uploadV2` method, it might be helpful to update the documentation on the website concerning the method, how to use it, a sample response, etc. Thank you!

### List any relevant URLs

- https://api.slack.com/methods/files.upload

**Comment by seratch** [comment]
Thank you so much for taking the time to send this feedback! Indeed, the api document page should have links to v2 information such as https://slack.dev/node-slack-sdk/web-api#upload-a-file I will talk to the team maintaining the site.

**Comment by caramelmelmel** [comment]
Hi @seratch I tried using `uploadV2` method but my channels cannot be found unlike v1 where I would not need to write my channel id. Can I ask if such capabilities of using channel name instead of channel id be added? the original v1 allows for channel name and channel id. Can I ask this capability be replicated?

**Comment by seratch** [comment]
@caramelmelmel Unfortunately, there is no plan to enable developers to pass a channel name instead of channel ID to the v2 API endpoints. Only long-lived APIs such as chat.postMessage and files.upload allow channel name as the parameter to specify what the channel is. A channel name can be renamed at any time, therefore it's not robust enough for long term maintenance. For this reason, newer endpoints accept only channel IDs and that's the same for the v2 file uploading functionality. I understand this is not convenient for you, but it'd be appreciated if you could understand this.

**Comment by filmaj** [comment]
These documents were updated on the API site. Closing.
