### ISSUE TITLE
No more OpenAPI specifications?

### ISSUE THREAD

**Issue by fab-mindflow** [slackapi/node-slack-sdk#1836]
Sincerely sorry for the request here.

We used (and we continue to rely) for years on the great Slack OpenAPI/Swagger specifications when integrating with Slack. However, the associated [Github project](https://github.com/slackapi/slack-api-specs)  has been recently archived (and wasn't active for a long time). Sadly 😢, we can't find another official source. We believe it's critically important to maintain 3rd party providers some API dynamic discovery mechanism (API generation, automation, AI, and more).

Have you switched privately for this handy specifications? Any plan to expose it again publicly? Should we go through a partnership to get it? 

Thanks in advance.

**Comment by seratch** [comment]
Hi @fab-mindflow, thank you for writing in!

We are sorry about the OpenAPI initiative's quality. As you know, it didn't go well; therefore, we had to terminate it. Additionally, there is no similar active initiative within Slack internally.

The only thing I can mention is that we are generating web API response types using our Java SDK's automated e2e tests towards the production API endpoints. We use an open-source tool called "quicktype" for auto-generating TypeScript code using the Java SDK outputs:
* The testing module to generate the input JSON data for quicktype: https://github.com/slackapi/java-slack-sdk/tree/main/slack-api-client/src/test/java/util/sample_json_generation
* The JSON outputs: https://github.com/slackapi/java-slack-sdk/tree/main/json-logs/samples/api
* The script to run quicktype for the `@slack/web-api` package: https://github.com/slackapi/node-slack-sdk/blob/main/scripts/generate-web-api-types.sh
* The generated TypeScript code: https://github.com/slackapi/node-slack-sdk/tree/main/packages/web-api/src/types/response

I understand this won't be a substitute for the OpenAPI/Swagger integration you wanted at all. Just wanted to mention this for your information. I hope this can be of help to some.

Let me close this issue here as the Deno SDK does not have anything further we can do for you. Thanks again for taking the time to write in and for utilizing our platform for such a long time!

**Comment by fab-mindflow** [comment]
Thanks for the reply.

I have also used Quicktype in the past ourselves. Yes, it's quite unfortunate the OpenAPI has been stopped (our Slack biding will be disrupted by this, it wasn't perfect but covered most of important endpoints). Moreover you have it all in the API documentation that you need to maintain anyway (docs is not part of quicktype binding...). Not arguing as it's your choice but there are plenty of use cases that SDKs will never cover (bleeding edge example: AI automation). Hope your engineering can think about it.

**Comment by dontgitit** [comment]
Since this initiative was discontinued, we built a tool that auto-generates an OpenAPI 3.1 spec directly from the TypeScript AST of the official `@slack/web-api`, `@slack/bolt`, and `@slack/types` packages using [ts-morph](https://github.com/dsherret/ts-morph).

A GitHub Action regenerates it weekly against the latest SDK.

**Repo:** https://github.com/connectstrata/slack-openapi-generator

The generated spec can be grabbed directly: [`slack-openapi-spec.json`](https://github.com/connectstrata/slack-openapi-generator/blob/main/slack-openapi-spec.json)
It includes Web API endpoints as well as Events/Actions/Shortcuts webhooks.
