### ISSUE TITLE
Getting Connection failed "not_allowed_token_type 

### ISSUE THREAD

**Issue by pm-radez** [slackapi/node-slack-sdk#1851]
We are getting 
```
level=error msg="Connection failed "not_allowed_token_type" slack.SlackErrorResponse{Err:"not_allowed_token_type", ResponseMetadata:slack.ResponseMetadata{Cursor:"", Messages:[]string(nil), Warnings:[]string(nil)}}" prefix=slack 
```

we have create new app as well but didn't work for us I have also shared the matterbridge.tomal file below

```
[slack]
[slack.test]
Token="xoxb-we have this token"
PreserveThreading=true
PrefixMessagesWithNick=true

[nctalk.cloud]
# The location of your Nextcloud instance with Talk installed
Server="https://nextcloudtalk.com"
Login="username"
Password="password"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="slack.test"
channel="general"

[[gateway.inout]]
account="nctalk.cloud"
channel="syhskost"
```

**Comment by zimeg** [comment]
Hey @pm-radez 👋  I'm not so familiar with Nextcloud or matterbridge, but the `not_allowed_token_type` error happens when an unexpected token is used with certain API methods. In this case, it's not super clear which method is returning this error, but the use of a bot token is a nice hint!

It might be that matterbridge support with Slack isn't working right now - https://github.com/42wim/matterbridge/issues/964#issuecomment-2239004492 - and based on that wiki it seems that [Classic Slack apps](https://github.com/42wim/matterbridge/wiki/Slack-bot-setup#create-the-classic-slack-app) are recommended for new setups while [creation of new Classic Slack apps has been discontinued](https://api.slack.com/changelog/2024-04-discontinuing-new-creation-of-classic-slack-apps-and-custom-bots) since June 4. 

If you have insight into the API methods being called that's returning this error, I'd be happy to troubleshoot. Otherwise, I'm not immediately sure of what might be causing this 🤔
