### ISSUE TITLE
The 'credentials' field on 'RequestInitializerDict' is not implemented.

### ISSUE THREAD

**Issue by emersonlaurentino** [slackapi/node-slack-sdk#1868]
I'm using hono, bun and cloudflare wrangler, I'm getting this error when I use `web-api`.

```bash
AxiosError: The 'credentials' field on 'RequestInitializerDict' is not implemented.
```

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

```bash
    "@slack/web-api": "^7.3.1",
```

#### Node.js runtime version

```bash
node: v20.12.0
bun: 1.1.22
```

#### OS info

```bash
roductName:            macOS
ProductVersion:         14.6
BuildVersion:           23G80
Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:41 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T6000
```

#### Steps to reproduce:

Any request is giving this error, examples of requests I'm using:

- `web.oauth.v2.access`
- `web.team.info`
- `web.conversations.list`

### Expected result:

Just work!
### Actual result:
<img width="412" alt="Screenshot 2024-08-08 at 12 37 39" src="https://github.com/user-attachments/assets/7480b04b-0201-468d-aa67-e65d108a1146">

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @emersonlaurentino! Thanks for your question! 🙌 

Based on the error, this seems like an issue with the Cloudflare Workers SDK. I found this related issue [here](https://github.com/cloudflare/workers-sdk/issues/2514). The good news is, since it looks like you're using Axios, [someone release a PR](https://github.com/axios/axios/pull/6533) for a fix for this issue for Axios ~1 hour ago!

In the meantime, while that's getting reviewed, merged, and released, [someone](https://github.com/cloudflare/workers-sdk/issues/2514#issuecomment-2178070014) suggested this approach:
> on the server-side i just check if credentials are supported and set them to undefined if not
```
const isCredentialsSupported = "credentials" in Request.prototype; 
fetch("...", { credentials: isCredentialsSupported ? "include" : undefined })
```

maybe try the above and see if it works with your use case?

**Comment by seratch** [comment]
@emersonlaurentino 
Even after resolving this specific error, you'll encounter more errors with Bun and Cloudflare Workers because this project focuses on Node.js runtime use cases. I understand you prefer first-party tools, but I created third-party libraries to build your Slack apps on edge function platforms. Please consider using the alternative solution this time. See https://github.com/slackapi/node-slack-sdk/issues/1603#issuecomment-1606541205 for more details.
