### ISSUE TITLE
How do I scale this?

### ISSUE THREAD

**Issue by thelinuxlich** [slackapi/node-slack-sdk#231]
It's just spawning processes whenever bottleneck happens and be happy?

**Comment by DEGoodmanWilson** [comment]
Howdy! Could you be more specific about what you are seeing, and what you were expecting to see? Along with steps to reproduce?

**Comment by aoberoi** [comment]
i have a few comments about scalability, specifically horizontal scalability.

1. using the new Events API for processing events rather than RTM gives you the ability to use traditional HTTP load balancers to scale. we released a dedicated node module for using it: [`@slack/events-api`](https://github.com/slackapi/node-slack-events-api).

2. the biggest challenge for scaling the RTM client would be the datastore API, since getting state out of the process is necessary for the approach you mentioned (spawning new processes). if you have any thoughts or input about this problem, join the discussion in #330.
