### ISSUE TITLE
not able to call web api method "files.comments.delete" (or other comments methods)...

### ISSUE THREAD

**Issue by nohir0** [slackapi/node-slack-sdk#255]
looks like files.comments methods are not possible to call from web api wrapper?
I am sure that I pass the correct parameters, but the TypeError anyway indicates that files.comments methods are undefined?

/home/bot/bin/bot_a/index.js:313
    web.files.comments.delete(message.file.id, message.comment.id, function ()
                             ^
TypeError: Cannot call method 'delete' of undefined

Edit: This is the init procedure for my code - just for info:

```

var WebClient = require('@slack/client').WebClient;
var web = new WebClient(web_token);
[...snip...]
  if (message.subtype == 'file_comment') {
    console.log('file comment file id: ', message.file.id); // delivers correct ID from message
    console.log('file comment id: ', message.comment.id); // delivers correct ID from message
    web.files.comments.delete(message.file.id, message.comment.id, function () {}); // throws above error
    web.files.comments.add(message.file.id, 'TEST COMMENT...', function () {}); --> also not possible... same error...
  }
[...snip...]
```

This is different from any other web api methods I can call without issues, like web.files.delete a.s.o.
Do I miss something?
Thanks4help

**Comment by Everesty** [comment]
Ahaha, this is probably caused because [the facet](https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/web/facets/files.comments.js#L13) defines it's name as `"files.comments"` and the setter for facets sets with `this[newFacet.name] = newFacet;`. That means that what you want is actually `web['files.comments'].delete` currently.

I suspect this is just a bug and should be fixed in the future, though.

**Comment by nohir0** [comment]
great, indeed that's exactly the point... impressed from your quick root cause findings! :P

as a github newbie I may ask:
shall I close the issue now, since it is solved for me with your workaround - or keep it open? because it is still to verify how to handle this properly...

**Comment by Everesty** [comment]
> great, indeed that's exactly the point... impressed from your quick root cause findings! :P

I've gone through the library quite a number of times :P Recognized what the issue was from prior knowledge.

> shall I close the issue now?

Nah, keep it open. One of the maintainers will see it and fix it (or label it), or someone else will submit a pull request fixing it. After that pull request is accepted, the maintainer should also close this issue.

I'd go ahead and submit the pull request but I'm busy for a little. If nobody gets around to it in a few hours, I'll probably do it then.

**Comment by DEGoodmanWilson** [comment]
Thanks for this, y'all! I'll be following up just as soon as I fix one blocking issue…
