### ISSUE TITLE
Make using a proxied transport much easier.

### ISSUE THREAD

**Issue by Iskander495** [slackapi/node-slack-sdk#286]
Hello,

I did not find an example of how you can send a message to slack using a proxy.

He found references in request.js, but did not understand its use.

Thank you in advance!

**Comment by Everesty** [comment]
I've actually answered this exact question in the past, but my previous answers aren't very great so I'm going to abuse this opportunity and give you a great answer.

The answer you're looking for depends on whether or not you're using the RTM client or the web client (they both have separate ways of proxying requests).

If you're trying to proxy with the web client then you need to pass a proxy transport to the web client (or RTM client) through **the `transport` option**.

This SDK does provide such a proxied transport: `proxiedRequestTransport` in `lib/clients/transports/request.js`. `proxiedRequestTransport` is a function that accepts a URL and returns a function that you can pass to the web client (or RTM client) to proxy requests to the slack API through your provided proxy URL.

Put in easy-to-understand-code code:

```js
var WebClient = require('@slack/client').WebClient;
var proxiedRequestTransport = require('@slack/client/lib/clients/transports/request').proxiedRequestTransport;

var client = new WebClient(token, {
  transport: proxiedRequestTransport('your proxy url')
});
```

If you're trying to proxy with the RTM client, however, then you have two steps:

1. Making the RTM websocket go through the proxy.
2. Making the call the RTM client makes to the web go through the proxy. (see above)

The second step is easy and is the same as the above case with the web client: supply the RTM client with a `transport` option that uses the function returned by `proxiedRequestTransport`.

As for the first step, it's very needlessly complicated (in reference to what it *could* be). Currently, you need to pass a function that accepts a socket URL and pass that socket URL to the transport exported by `lib/clients/transports/ws.js` that URL and an options object that contains an option named `proxyURL`.

*(technically you can also just do the socket transport implementation yourself, but I'm going to ignore that option because it seems silly)*

So, in whole, this (currently) has to be done like this:

```js
var RtmClient = require('@slack/client').RtmClient;
var proxiedRequestTransport = require('@slack/client/lib/clients/transports/request').proxiedRequestTransport;
var wsTransport = require('@slack/client/lib/clients/transports/ws');

var client = new RtmClient(token, {
  // To proxy opening the client.
  transport: proxiedRequestTransport('your proxy url'),
  // To proxy RTM messages.
  socketFn: function(socketURL) {
    return wsTransport(socketURL, { proxyURL: 'your proxy url' });
  }
});
```

Obviously, this is a pain and could very well change (hopefully for the better) in the future so keep an eye open.

---

@DEGoodmanWilson: proxying with the clients is really hard, especially importing the proxy objects.

In general, what's needed to be done:
* Export `lib/clients/transports/ws` and `lib/clients/transports/request` in `index.js` (aka what people get when they `require('@slack/client.js')` so they're easier to access.
* Add an option that'll help pass a proxy url to the RTM client's `_socketFn` (be it a `proxyURL` option in the client or an option for an object that'll be passed to the transport function [like it expects](https://github.com/slackapi/node-slack-sdk/blob/master/lib/clients/transports/ws.js#L12)).
  * Maybe likewise in theory with the RTM client for the web client: don't force the user to provide a proxy transport and instead just make the default transport accept a proxy URL/options object. Whichever is chosen, make it consistent with the RTM client.

**Comment by aoberoi** [comment]
@Everesty I just wanted to say we really appreciate you spelling out the steps in detail. I'm fairly new to this project here at Slack and I hadn't pieced that much together myself yet.

I'm going to change some of the metadata on this issue so we can prioritize your suggestions.

**Comment by aoberoi** [comment]
related issue: #370. this might even be a dup with an oversimplified view of how things work. i think this issue may be more authoritative.
