### ISSUE TITLE
file upload example is broken

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#310]
* [ ] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> The example found at https://slackapi.github.io/node-slack-sdk/basic_usage#uploading-a-file does not work. "`fs.createReadStream(filePath)` should be `fs.createReadStream(fileName)`" (thanks @mhahn)

#### Reproducible in:
node slack sdk version: *
OS version(s): *
Device(s): *

#### Steps to reproduce:

1. Try the example code, witness failure.

### Expected result:
> a file to be uploaded successfully

### Actual result:
> runtime failure

**Comment by Everesty** [comment]
I believe the description given isn't fully accurate: `fs.createReadStream(filePath)` should indeed be itself, but `filePath` should instead point to _a file_ rather than _a directory_.

The file name and path _are_ different (or at least can be, and that should be shown off) so the change should definitely not remove the `filePath` variable.

Just clarifying.
