### ISSUE TITLE
Question: Timeline for Events API support?

### ISSUE THREAD

**Issue by jfyzhao** [slackapi/node-slack-sdk#311]
Is there a rough timeline of when support for the Events API will be available?

Thanks!

**Comment by aoberoi** [comment]
I'm glad you asked. The work for it has been ongoing and almost complete!

We thought really hard about how the SDK could and should work with the Events API, and in short, we decided on making a separate module that could be used standalone and then we'd plug it into this SDK to give you a complete package; your choice. 

The standalone module is feature complete and you can take a look at it github.com/slackapi/node-slack-events-api. It's not released yet because we need to put some finishing touches on it, but we'd love to hear any feedback you might have today. 

I anticipate the full support to land in this SDK in no more than a couple weeks.

**Comment by jfyzhao** [comment]
That's awesome to hear! Would it be possible to put the events module in the npm registry so we can start development with it?

Thanks for all the hard work!

**Comment by aoberoi** [comment]
good news! we've just released a new [Slack Event Adapter module for Node](https://github.com/slackapi/node-slack-events-api). you can get it on npm with `npm install @slack/events-api`).

its a pretty basic utility that helps you set up listeners and adhere to some best practices. we look forward to enhancing it with new features (read: you feedback and ideas welcome) and potentially integrating it into this package in the future.
