### ISSUE TITLE
Adopt pagination standard with a default page size for methods which support it

### ISSUE THREAD

**Issue by hparadiz** [slackapi/node-slack-sdk#343]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> Large slack organizations with many thousands of users cause the slack API to throw an HTTP 500 error when running users.list through the WebAPI.
> The API runs with no options by default and other slack OSS projects use the api call with default settings.

#### Reproducible in:
[hubot-slack](/slackapi/hubot-slack) version: latest
OS version(s): any
Device(s): any

#### Steps to reproduce:

1. Run users.list against an organization with thousands of users
2. See users.list throw a 500 http error
3. See users.list timeout without handling the error

### Expected result:
> e.g. Users.list to add a limit field to it's options by default and detect the output containing offset in the json return. Then hit the api again until the user list does not return offset signifying that you have reached the last page.

### Actual result:
> e.g. Does not handle http 500 and times out at 300 seconds

### Notes
> I reported this issue in the hubot-slack repo but after reading the source code I feel that the fix is more appropriate in this repo instead.

>hubot-slack loads the entire users list into memory on load which seems insane to me when our organization has thousands of users and my bot is only in one or two channels with maybe 20 users. A user list by channel that loads on channel join would be way better.

**Comment by aoberoi** [comment]
thanks for the issue report @Akujin. i agree that 500 errors on large teams is quite unacceptable. unfortunately, without a pagination solution as you recommended at the API Platform level, there's nothing we can do in the SDK to mitigate this situation. but be aware that we are working on a pagination solution at Slack so we can prevent these types of issues from happening.

**Comment by Akujin** [comment]
Thank you for the detailed response.

So when I submitted a support ticket initially I was actually told of undocumented API variables for `users.list`.

> 1. Pass a `limit` argument to restrict the number of entries returned. This should just be a number — "1000" is probably a good one to start with.
> 2. When a subsequent page exists, we will return an `offset`
field in the response. You can then call the next set of results with the 
`offset` from the previous response to get to the next page. If no `offset` is provided, you have reached the last page. This way, you can recursively call the API for as long as an 
`offset` exists in our response.

I know this isn't true pagination since you can't just call page N but it would allow `users.list` to handle large orgs and at least in this use case you're trying to pull the entire list anyway. And it can be done now with no changes to the slack api.

---

I'm a little perplexed by `SLACK_CLIENT_OPTIONS`. I can't find where it reads `process.env.SLACK_CLIENT_OPTIONS`.

I tried searching for it in https://github.com/slackapi/hubot-slack/ but only found it as a regular variable and not an environmental variable.

Right now I'm just commenting out these three lines of code to prevent users.list from being called
https://github.com/slackapi/hubot-slack/blob/master/src/bot.coffee#L56-L58

I want to avoid forking hubot-slack just to edit `SLACK_CLIENT_OPTIONS` so if there's some example usage of `SLACK_CLIENT_OPTIONS` as an environmental variable that'd be great.

**Comment by aoberoi** [comment]
@hparadiz that's my fault actually, i always thought it was read from an environment variable and now i see that it's not. i've created slackapi/hubot-slack#421 to track getting this implemented. if you have the ability and would like to help, i'd be happy to assign the task to you. otherwise it might take a few weeks to get this out given current priorities.

the undocumented pagination technique is not something i'm willing to implement in the SDK because **it will break** and the new pagination technique is right around the corner. in the meantime, i'm thinking the following changes would comprise support for this feature:

*  change the implementation of paginated endpoints to use a reasonable default page size (e.g. 1000) and only invoke the callback or resolve their promise once all pages are iterated.
*  if pagination options are passed into the individual method calls (e.g. `{ limit: 20 }`), then invoke the callback or resolve the promise after the first call. this should allow the user to iterate with custom logic.

feedback on this feature is welcome!

**Comment by aoberoi** [comment]
This has become more relevant since the pagination spec is now standard across API methods. See https://slack.engineering/evolving-api-pagination-at-slack-1c1f644f8e12.

Here are a few of the methods that could benefit:
* conversations.history
* conversations.list
* conversations.members
* conversations.replies
