### ISSUE TITLE
Add username to postMessages

### ISSUE THREAD

**Issue by zafar-saleem** [slackapi/node-slack-sdk#376]
I am successfully sending messages to my channel via node-slack-sdk webClient. However, messages appeared on slack as "Slack API Test" username. I would like to setup my username and post all messages as my username. How can I set slack username for postMessages using webClient?

**Comment by aoberoi** [comment]
i assume since you closed the issue that you found the solution, but for others that find this question i'll go ahead and spell it out.

you probably saw Slack API Test because you were using a tester token. You need to generate your own tokens. You can use a Bot access token (`xoxb-...`), a User access token (`xoxp-...`), or the new type we just introduced, a Workspace token (`xoxa-...`). Depending on which type of token you use, the method you are calling, and the options you pass in, the [Authorship](https://api.slack.com/methods/chat.postMessage#authorship) of your message will change.

you most likely want to create an app with a bot user, so that you can get a bot access token, and then post without any additional options to use the bot's identity.
