### ISSUE TITLE
Install fails with 401 on Node 8

### ISSUE THREAD

**Issue by Restuta** [slackapi/node-slack-sdk#377]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
Just doing `npm install @slack/client`

getting
```
npm ERR! code E401
npm ERR! 401 Unauthorized: @slack/client@latest
```

```
❯ node -v && npm -v
v8.1.3
5.3.0
```

#### Reproducible in:
version: latest as of today
OS version(s): OSX 10.11.3
Device(s): Mac Book Pro 2011

#### Steps to reproduce:

1. `npm install @slack/client`

### Expected result:
Dependency added to my project.

### Actual result:
401 error.

**Comment by clavin** [comment]
This is definitely not an issue on our end, but rather on NPM's end (ish). My guess is that you're having some kind of (company?) proxy issues, i.e. npm is trying to access its registry but can't because it can't authorize to the local proxy.

Upon a simple google for "npm 401" I also felt like [this might be a possible solution](https://github.com/npm/npm/issues/12758#issuecomment-220171956).

Nevertheless, this issue *technically* isn't related to this repository/package.

(also, sorry about the delay in response!)

**Comment by Restuta** [comment]
alright, thanks for explaining

**Comment by jannhama** [comment]
@clavin Do you know who creates .npmrc file? This happened to me as well with a project that was working just fine earlier.

**Comment by aoberoi** [comment]
@jannhama the `.npmrc` file is usually either created by a user running `npm config [--global]` or by hand-editing it to suit a specific project. there's more info in the [documentation here](https://docs.npmjs.com/files/npmrc).

is there a problem that happened that we can help with?
