### ISSUE TITLE
Missing web.channels.replies() facet?

### ISSUE THREAD

**Issue by mismith** [slackapi/node-slack-sdk#378]
Doesn't seem to be listed in here anywhere: https://github.com/slackapi/node-slack-sdk/blob/master/lib/clients/web/facets/channels.js

Should be simple/easy enough to implement, any idea why this hasn't already been done?

**Comment by aoberoi** [comment]
you're totally right. didn't already happen mostly because the we didn't get ahead of Threads when that feature launched. thanks for finding that!

it's a relatively easy copy/paste job to implement this. i will put it in the queue to be worked on, but that queue is kind of slow these days, so contributions welcome.

FYI we're working on a solution that will autogenerate these facets in the future so this sort of an issue doesn't happen again.

**Comment by aoberoi** [comment]
fixed in #398!
