### ISSUE TITLE
Storing RTM Session in database. Functions not working correctly.

### ISSUE THREAD

**Issue by yousefissa** [slackapi/node-slack-sdk#383]
Hello.

I am trying to store the RTM session that I am creating in a database so that I don't have to keep creating new ones on every connect while leaving the old ones open. Is there anyway I can store the RTM session in a mongodb and access the functions like .disconnect() and .start()?

I've tried but have been getting a `session.disconnect` is not a function.

Here is how my schema looks

    var mongoose = require('mongoose');

    var rtmSchema = new mongoose.Schema({
	    session: mongoose.Schema.Types.Mixed
    });

    module.exports = mongoose.model('rtmModel', rtmSchema);

**Comment by aoberoi** [comment]
@yousefissa i'm not sure what you mean by the "RTM session", can you clarify?

FYI the the RTM client currently supports a [`SlackDataStore`](https://github.com/slackapi/node-slack-sdk/blob/master/lib/data-store/data-store.js) interface for storing team data associated with a specific connection. It sounds like this is what you want, and you'd have to implement an object with that interface that can store to a mongo backend.

However, keep in mind that we've been having discussions about redoing or removing the `DataStore` abstraction in the next major version of this package.

**Comment by yousefissa** [comment]
Thanks for the reply!

When I call this: `rtmSession = new RtmClient(their slack access token)` I want to keep track of that session in the database so I do not create a new one every time the same user connects to a socket. Is there a better way to do that?

**Comment by aoberoi** [comment]
Got it, thanks for clarifying.

First, I would avoid calling that a session, its an instance of the `RtmClient` class, so I'd call it a client.

Second, it's not something that can be "saved" and then "loaded" to a database because it doesn't represent data. It represents a stateful connection to Slack; `rtm.start()`. The way we typically work with these in node is to keep references to client objects in memory. Since the process is long running, those objects will stay alive as long as the process does, and they won't disappear unless you specifically discard/delete the reference. If you have many clients in your program, the simplest thing to do would be to store them in an object that is keyed by some identifying information (like a user ID), look up the reference to the client when you need it, and then call whatever methods on it that you need.

Lastly, I just want to add that if you are handling many connections, its almost always a better design to use a combination of the [Events API](https://github.com/slackapi/node-slack-events-api) and the [Web API](https://github.com/slackapi/node-slack-sdk#posting-a-message-with-web-api) rather than the RTM API. You wouldn't have any stateful connections to worry about. All the events would be delivered through HTTP requests to your application and your app's actions would be sent as HTTP requests to Slack.

**Comment by yousefissa** [comment]
Perfect. Thanks so much for the advice!
