### ISSUE TITLE
Use of WebClient to perform oauth.access not allowed without an API token

### ISSUE THREAD

**Issue by nogurenn** [slackapi/node-slack-sdk#404]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> This came up while I was developing an AWS Lambda function invoked by Slack OAuth's `redirect_uri` that will continue the OAuth dance. I thought it was counterintuitive that the WebClient doesn't allow tokenless invocation of `oauth.access()` (like a static/class-level method) and wondered if this can be seen as an enhancement.

**Comment by aoberoi** [comment]
@nogurenn that seems like a reasonable enhancement request!

just FYI, you could instantiate a `WebClient` without a token and invoke the `web.oauth.access()` method. i know you are asking for a static method.

if we do implement this API, it seems like the most straightforward path would be instantiate a "temporary" instance of the WebClient and just invoke that method. otherwise, we would have to initialize a whole bunch of resources/state and that would duplicate the code in the constructor.

**Comment by nogurenn** [comment]
It feels more natural to invoke it "statically." If it works, it works! 💯

**Comment by aoberoi** [comment]
closing since this seems to work in v3, and v4 is now out. issue #482 is relevant.
