### ISSUE TITLE
Does not support optional include_locale parameter

### ISSUE THREAD

**Issue by krewllobster** [slackapi/node-slack-sdk#421]
### Description

Slack recently (September, 2017) added an optional parameter "include_locale" to a number of web api calls including the following (issues with each as noted): 

- channels.info: no options parameter in method, passes null to makeAPIcall
- conversations.info: allows options parameter, but passes null to makeAPIcall
- groups.info:  no options parameter in method, passes null to makeAPIcall
- im.info: method does not exist in lib
- im.open: no options parameter in method, passes null to makeAPIcall
- rtm.start: no issues here!
- users.info: no options parameter in method, passes null to makeAPIcall
- users.list: no options parameter in method, passes null to makeAPIcall

Should be a relatively simple fix to add opts to the affected facets and methods. However, it may cause issues for people who have the second parameter as optCb at the moment. Anyone calling users.info(user, optCB) will be adversly affected by a change to users.info(user, opts, optCB).

Might the fix be to include an "opts" input for all methods and check if opts is a function, and if so, make it the callback? This could also be addressed by passing objects to the lib methods rather than parameters. 

Sorry if this is at all not clear. Relative beginner here. Thanks!

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Attachments:

https://api.slack.com/changelog/2017-09-locale-locale-locale

**Comment by aoberoi** [comment]
@krewllobster thanks for reporting! your issue is beautiful and very clear 👍 

so, the crux of this issue is already identified in #395, but you did add some relevant information. there's a few methods that i didn't catch in that issue, so i'll add them. also, the `conversations.info` and `im.info` issues can be resolved with a quick update.

regarding the dynamic argument type-checking solution, i'm more in favor of the solution in #381. that being said, i'm open to a discussion and can be convinced otherwise. unfortunately, we don't have a release planned until late January that will address that, but we would welcome and accept a contribution.

i'll close this issue as a duplicate, because that's how i feel it mostly is, but i'll be sending a PR to fix the two methods where its easy. feel free to discuss any other points in this issue.
