### ISSUE TITLE
Request documentation for JSON Web API methods for node-slack-sdk

### ISSUE THREAD

**Issue by cbilliau** [slackapi/node-slack-sdk#424]
### Request for the addition of documentation on using JSON with node-slack-sdk for Web API methods

With the [announced support for slack Web API write methods](https://api.slack.com/changelog/2017-10-keeping-up-with-the-jsons) of properly formatted JSON, this request is for the creation of support documents on using JSON with the node-slack-sdk.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by aoberoi** [comment]
hey @cbilliau thanks for the request!

in general i'm 👍  on getting JSON-based write methods implemented in the WebClient, but I'm confused about how you see documenting this functionality would look. users of this SDK wouldn't really see any changes because the API for interactive with the Web API though the SDK is identical. is there something i'm missing?

as far as getting this implemented, at this point i see it as a low priority clean-up task since there's no new functionality here. if someone is keen and wants to contribute though, i'd be happy to merge that in.

**Comment by cbilliau** [comment]
OK. I wasn't sure if the JSON changes impacted anything. I'll close this out then.
