### ISSUE TITLE
add RTM events for member_joined_channel and member_left_channel into enumeration

### ISSUE THREAD

**Issue by oneeman** [slackapi/node-slack-sdk#448]
### Description

Some event types are missing in https://github.com/slackapi/node-slack-sdk/blob/master/lib/clients/events/rtm.js .

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Some event types are missing from https://github.com/slackapi/node-slack-sdk/blob/master/lib/clients/events/rtm.js .  That file says it's autogenerated, but I don't know where or how.  At any rate, examples of missing event types are `member_joined_channel` and `member_left_channel`, which are included in the RTM (according to the docs, and verified by me today in practice), but are not included among event types in the SDK.

I consider this a bug rather than a documentation issue in as much as the event type constants are included but are incomplete, and this is a matter of javascript code rather than documentation.

**Comment by aoberoi** [comment]
thank's for the report. i just noticed this myself as i was writing the example here: https://slackapi.github.io/node-slack-sdk/rtm_api#subscribing-to-presence-updates.

sorry about the misleading code comments. the truth is these values _used to_ be generated via a script, but for the last 18 months have been maintained by hand. that leads to some of the newer event types and facets going out of date.

at the moment, the workaround is to just use the strings directly as the event names (as i did in the example i liked above).

i'm happy to take a PR to fix this. it would be awesome if the PR could also update that example, too! i'm not prioritizing this into a feature release at the moment because the majority of our development bandwidth right now is focused on shipping v4.
