### ISSUE TITLE
Register handler for specific errors

### ISSUE THREAD

**Issue by wilhelmklopp** [slackapi/node-slack-sdk#472]
### Description
👋 It would be cool if there was a way to register a handler for specific errors, so that we can take an action when they occur. As an example, for the [GitHub Integration](https://github.com/integrations/slack) we want to disable an active subscription whenever we get an `is_archived` error from any of the 5+ places where we invoke chat.postMessage.

We're thinking something like:
`client.on('is_archived', disableSubscriptions)`

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
thanks for sharing the idea! also, for clarification we are talking about the WebClient here, right?

my first impression: i'm not a huge fan of dynamically generated (via the platform's response) event names. would something like the following still interest you?

```javascript
web.on('error', (error) => error.data && error.data.error === 'is_archived' ? disableSubscriptions());
```

we could also consider going one step further, by emitting specific ErrorCode types:

```javascript
web.on('error:PlatformError', (error) => error.data.error === 'is_archived' ? disableSubscriptions());
```

**Comment by bkeepers** [comment]
I think `web.on('error', fn)` would be sufficient for our needs.

**Comment by wilhelmklopp** [comment]
> thanks for sharing the idea! also, for clarification we are talking about the WebClient here, right?

yep 👍

**Comment by aoberoi** [comment]
cool! this isn't on the immediate action list right now, but if a PR shows up, I'd gladly merge 😄

**Comment by aoberoi** [comment]
@bkeepers @wilhelmklopp i have a question for you both on the use case. would it make sense for the `'error'` event to fire for each retry, or when the retires are complete and the client is giving up? i'm leaning towards the latter, since you probably wouldn't expect to handle duplicate errors for the same underlying call to `WebClient#apiCall()` (or any of its named aliases).

this implies that if you want to know about the error relatively soon, you'd have to utilize the `retryConfig` option on initialization. the default retry policy could (in the worst case) retry for up to 30 minutes (maybe we should add a feature so this can be overriden for individual calls).

also, as alluded to in #451, if the request is being retried due to rate-limiting, the client doesn't follow the `retryConfig` policy. right now, we queue up essentially a new task to make the API request. you can already observe this using the `'rate_limited'` event, so i'm leaning towards no `'error'` event for rate limit triggered retries. does that sound right?

**Comment by aoberoi** [comment]
Hey there, we never nailed down the exact requirements of this API. Also, there haven't been any other requests for similar functionality. @wilhelmklopp @bkeepers, if you all could help us understand the requirements, we'd be happy to work on this. But for now, I'm closing the issue to keep things tidy.
