### ISSUE TITLE
presence_change event not emitted/received after approx. 1-2 days 

### ISSUE THREAD

**Issue by lipp** [slackapi/node-slack-sdk#515]
### Description

I have a process which is supposed to run "forever" as a service. It listens for "message" events
and subscribes to user the user presence thus listening for "presence_change" events too.

After 1-2 days, the process stops emitting "presence_change" events. It still emits "message" events though. 

### What type of issue is this?
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirement
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

`@slack/client` version: 4.0.0

node version: 9.8.0

OS version(s): Linux (Docker)

#### Steps to reproduce:

1. `rtm.subscribePresence(ids)`
2. `rtm.on('presence_change', function onPC (){}) ; rtm.on('message', function onMessage (){})`
3.  wait 1 - 2 days.

#### Expected result:

`onMessage` and `onPC` will be called when the respective event occurs/happens.

#### Actual result:

`onMessage` will be called (as expected), `onPC` will **NOT** be called on presence change of the respective users.

**Comment by lipp** [comment]
Maybe the subscribePresence is not automatically resend on "reconnect"?

**Comment by aoberoi** [comment]
@lipp i haven't seen this issue myself, but it would be expected behavior that the presence updates stop emitting after a reconnect.

can you try placing the `rtm.subscribePresence(ids)` part of your code inside a handler for the `ready` event? i'd love to know if that fixes your problem.

i just noticed this would also be a problem in the following documentation example: https://slackapi.github.io/node-slack-sdk/rtm_api#subscribing-to-presence-updates

lastly, i can imagine implementing a feature to more intuitively handle presence subscriptions in `RTMClient`. besides issuing the `presence_sub` message on reconnects, the client could also store the list of user IDs for which a subscription is active and provide methods to add or remove IDs to that list. i'll start a new ticket to capture this idea.

**Comment by lipp** [comment]
thanks @aoberoi . started a new test with the suggested modifications. reaching back in 1 - 2 days 
😃

**Comment by aoberoi** [comment]
@lipp any news?

**Comment by lipp** [comment]
@aoberoi yes, sorry for responding late! resubscribing on "ready" works like a charm.

```js
rtm.on('ready', () => {
  rtm.subscribePresence(ids)
})
```

would be nice to have this happen automatically behind the scenes as described in #517  :)

thanks!

**Comment by nikhila-3012** [comment]
@aoberoi Hi Ankur I am trying to build a bot with the same functionality and the same issue : After 1-2 days, the process stops emitting "presence_change" events. It still emits "message" events though. Could you help ?
