### ISSUE TITLE
Trigger Expires in >500milliseconds 

### ISSUE THREAD

**Issue by ChaddPortwine** [slackapi/node-slack-sdk#597]
**Goal**
Slack Event Subscription is hitting my Firebase Endpoint, and then, a Firebase Cloud Function is using `dialog_open` to open a dialog in Slack with some values from Firebase.

I am getting `body: { ok: false, error: 'trigger_expired' } `:

However, the logs in Firebase show the round-trip is less than 500 milliseconds. But, I don't see the trigger ID which wil log to the trigger_id from the first requst (see code below).
```
4:57:12.443 PM | info | helloWorld | body: { ok: false, error: 'trigger_expired' } 
4:57:04.163 PM | outlined_flag | helloWorld | Function execution took 254 ms, finished with status code: 200
4:57:03.910 PM | outlined_flag | helloWorld | Function execution started

```

When I trigger the Slack event again, I am getting `body: { ok: false, error: 'invalid_trigger' }`

This also happens fast enough, but a different trigger error, AND this time I **do** see the json.trigger_id, that I assume came from the Slack Event Subscription.

What is the matter with my trigger_id? Thanks!

Here is the Firebase Cloud Function:
```
import * as rp from "request-promise";
import * as functions from "firebase-functions";

export const helloWorld = functions.https.onRequest((request, response) => {
  return new Promise((_resolve, _reject) => {
    let json = JSON.parse(request.body.payload);
    console.log("json.trigger_id:", json.trigger_id);

    const options = {
      method: "POST",
      uri: "https://slack.com/api/dialog.open",
      body: {
        trigger_id: json.trigger_id,
        dialog: {
          callback_id: json.callback_id,
          title: "Request a Ride",
          submit_label: "Request",
          elements: [
            { type: "text", label: "Pickup Location", name: "loc_origin" },
            { type: "text", label: "Dropoff Location", name: "loc_destination" }
          ]
        }
      },
      json: true,
      headers: {
        "Content-type": "application/json; charset=utf-8",
        Authorization:
          "Bearer xoxp-secret"
      }
    };

    rp(options)
      .then(function(body) {
        console.log("body:", body);
      })
      .catch(function(err) {
        console.log("err:", err);
      });
    return response.status(200).json({ message: "Hello from Firebase" });
  }).catch(err => response.status(500).send(err));
});
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by ChaddPortwine** [comment]
I tried JSON.stringify:

`trigger_id: JSON.stringify(json.trigger_id),`

Now the logs and error are different:

```
5:33:24.512 PM | info | helloWorld | body: { ok: false, error: 'internal_error' }
5:33:23.565 PM | outlined_flag | helloWorld | Function execution took 13 ms, finished with status code: 200
5:33:23.559 PM | info | helloWorld | json.trigger_id: "406895248231.7467239747.7490e460213b3d65a44eef9f2e30c168"
5:33:23.553 PM | outlined_flag | helloWorld | Function execution started

```

I must be doing something dumb. Any guesses what?

**Comment by clavin** [comment]
From the [article on dialogs](https://api.slack.com/dialogs#interactive_triggers):

> Triggers expire 3 seconds after being issued to your app.

From your logs, it's apparent that it's taking over 3 seconds to respond to slack.

```
4:57:12.443 PM | info | helloWorld | body: { ok: false, error: 'trigger_expired' } 
4:57:04.163 PM | outlined_flag | helloWorld | Function execution took 254 ms, finished with status code: 200
```

Both log entries have a timestamp. That first one (the `info` line), when you get a response from Slack, shows a timestamp *8 seconds after* your function ends, which is shown in the second line.

Moving forward, I believe [this StackOverflow answer](https://stackoverflow.com/a/45515472/5767783) might shed some light as to what's occurring here.

That "254 ms" is not entirely false, but it's misleading. That measurement is done when your function *returns* (and resolves), rather than when it *completes execution*. In your function, you return a `Promise`, but that Promise resolves pretty much immediately.

The line before your return your 200 response, you make a request using `response-promise`, but you never wait for it to resolve. Here's a more basic example of what's happening:

```js
function washClothes() {
  return new Promise((resolve, reject) => {
    // put clothes in machine
    // add bleach/detergent
    // etc.
  });
}

function doChores() {
  return new Promise((resolve, reject) => {
    // !! this call to `washClothes` starts an asynchronous process,
    // !! but you never wait for it to complete!
    washClothes();
    // !! thus, the function continues onward before you finish (or even start!)
    // !! washing your clothes.

    return response.to(mom).message("finished chores!");
    // you just told mom you've finished something that you haven't even started!
  });
}
```

This isn't how Promises work--or at least, not how they should work. An amazing overview to using promises is explained in [this Google Developers article on them](https://developers.google.com/web/fundamentals/primers/promises).

To fix this, you should wait for the intermediate promise, then work off its result:

```js
function doChores() {
  // !! ta-da! we use the promise that `washClothes` returns, and wait for it to finish!
  return washClothes()
    .then(() => {
      // now the clothes (and other chores) are done!
      return response.to(mom).message("finished chores!");
    })
}
```

**Comment by ChaddPortwine** [comment]
@clavin Thank you for graciously providing support beyond the scope of the API. I've made some silly mistakes misusing promises and misreading logs. Once the code is sorted, I'll post what's working.

Thanks again!
