### ISSUE TITLE
Response from Firebase vs Express

### ISSUE THREAD

**Issue by ChaddPortwine** [slackapi/node-slack-sdk#634]
### Description

Using Firebase Cloud Functions/Express to respond to a slash command.

**Responce Success!**
* Slack slash command: /hello
`https://us-central1-myapp.cloudfunctions.net/helloWorld`
* Firebase: Receives `request` and `responds` to Slack
```
exports.helloWorld = functions.https.onRequest((_req, res) => {
  res.status(200).send("Hello from Firebase!").end();
});
```

**Responce Error 404**
* Slack slash command: `/go`
`https://us-central1-myapp.cloudfunctions.net/app/go`
* Firebase: Receives `request` and _passes_ the`request` to an Express route.
* Express Recieves `request` and `repsonds` to Slack
```
app.get("/go", (req, res) => {
  res.status(200).send("Hello from Express!").end();
});
exports.app = functions.https.onRequest(app);
```
---
I'm guessing I may need to authorize the `response header` coming from Express with slack auth secrets. 

1. Is this true?
2. Why do I get the `404 error` when routing to Express with `app.get()`? Firebase `onRequest` responds fine.
3. When is `web.chat.postMessage()` required? 

**Example Code**
Here is the Firebase Cloud Function

```
// Express
import express = require("express");
const app = express();
const cors = require("cors")({origin: "*"});
app.use("*", cors);

// Firebase Functions SDK
import functions = require("firebase-functions");

// Express route
app.get("/go", (req, res) => {
  res.status(200).send("Hello from Express!").end();
});

exports.app = functions.https.onRequest(app);

exports.helloWorld = functions.https.onRequest((_req, res) => {
  res.status(200).send("Hello from Firebase!").end();
});
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
Hi @ChaddPortwine 👋 

This is just a guess, but I _think_ you might just need to change the `app.get()` to `app.post()`, since Slack's slash command requests are mostly POST requests. For legacy custom integrations you chose between GET or POST, but for Slack Apps its always going to be POST.

Just FYI: i don't mind helping out with stuff like this, but I think a better avenue is the [Bot Developer Hangout](https://community.botkit.ai/) or emailing us (<developers@slack.com>) for questions like this that aren't actually related to this package. mostly because there are more 👀 in those places so your question would get answered even faster!

**Comment by ChaddPortwine** [comment]
app.post() is the answer!

@aoberoi Thank you for the tip about using the Hangout and email for support.
