### ISSUE TITLE
CLIENT_EVENTS  undefined

### ISSUE THREAD

**Issue by bitsflew** [slackapi/node-slack-sdk#679]
### Description

I'm trying to get a channel list using  the following code:

```

import { RTMClient } from '@slack/client';
const RTM_EVENTS = require('@slack/client').RTM_EVENTS;
const CLIENT_EVENTS = require('@slack/client').CLIENT_EVENTS;

async function sendMessage(messafe: string) {

 const rtm = new RTMClient('xoxb-...');
 const result = await rtm.start();

rtm.on(CLIENT_EVENTS.RTM.AUTHENTICATED,  (rtmStartData) => {
  for (const c of rtmStartData.channels) {
    if (c.is_member && c.name ==='general') { channel = c.id }
  }
  console.log(`Logged in as ${rtmStartData.self.name} of team ${rtmStartData.team.name}, but not yet connected to a channel`);
  });

...
}
```

The code connects without any issues, but throws an error because 'CLIENT_EVENTS' is undefined.
What is the correct way to import the constants?

**Comment by aoberoi** [comment]
Hi @bitsflew 

It looks like you’re trying to reuse some code that was written with v3.x of this package. We’re now shipping v4.x, and there are some changes that you’ll need to understand to adjust the code to work. You can find details about those changes [in the migration guide](
https://github.com/slackapi/node-slack-sdk/wiki/Migration-Guide-for-v4#rtmclient).

Specifically, there is no longer a `CLIENT_EVENTS` constant. You can use the string `'authenticated'` directly.

Can you point out where the code you’re reusing came from? I’d like to get it updated so that others who find the same code know about the changes in v4.x.

**Comment by aoberoi** [comment]
@bitsflew I’m glad you asked. This is because the default value of the `useRtmConnect` value changed from `false` to `true` in v4.x. 

While you could just set the option back to `false` yourself, i **strongly recommend not to do this**. The reason we changed the default is that in large teams, the connection has a greater chance of failing when this value is `false`. Instead, we recommend using the `WebClient` class to get a list of channels. There is an example of that here: https://slackapi.github.io/node-slack-sdk/web_api#getting-a-list-of-channels

If you only need to send messages to a single channel, one that the user picks when installing the app, then an `IncomingWebhook` is the easiest option. There’s an example here: http://slackapi.github.io/node-slack-sdk/incoming_webhook. 

Is there some other reason you’d like to use RTM to get this list? I’m happy to discuss other options too.

**Comment by bitsflew** [comment]
Almost there

web.channels.list() returns 'CFG2W9DAZ'   for the channel.
However the following code throws an 'invalid channel id' error:

```
const message = { type: 'message', channel: 'CFG2W9DAZ', text: 'hello' };
const result = await rtm.addOutgoingEvent(true, message.type, message);
```

**Comment by aoberoi** [comment]
once again, any reason for using the RTMClient to send a message? I'd recommend using the example here: https://slackapi.github.io/node-slack-sdk/web_api#posting-a-message

it looks like you are either migrating old code of your own, or following an outdated example. can you share where this code is coming from? i'd like to update any old examples.

**Comment by bitsflew** [comment]
I found the reason for the error!

The bot was not a member of the channel.

**Comment by aoberoi** [comment]
> Why RTMClient?
> I want to implement a Slack message post with continuously updating content and RTMClient seems the right choice for that.

Sure, you can use the `RTMClient` to send these messages, but I recommend the `WebClient` because it can also do this, and with less limitations (maybe you want to add attachments, or blocks, or something else in the future; `WebClient` knows how to retry when there's a network issue, etc).

`RTMClient` can still be used for the part of your app where you need to know when something happens in Slack. From your description, I'm not sure if "continuously updating" means "after every x amount of time", or "when something happens in some other system", or "when something happens in Slack". If its the last case, then `RTMClient` makes sense for just that part, but `WebClient` can still be used to send the message.

---

Glad you found the issue with the channel membership. I think we can improve the documentation to mention that when using the `bot` scope, you should make sure the bot user is in the channel.
