### ISSUE TITLE
Anyway to cancel the "User is Typing..." message after sent?

### ISSUE THREAD

**Issue by joshstrange** [slackapi/node-slack-sdk#704]
### Description

I figured out how to send the typing indicator as my bot but I have an issue now where the "Bot Name is typing..." is still showing after I've sent a message. I realize this is because I am sending the message via Web instead of RTM (where I am sending the typing indication) and the typing indicator goes away if I send a message via RTM. The problem is RTM doesn't support 2 big things I need:

1. Ability to "rename" the bot: Right now the bot's real name is (for example) "Generic Chat Bot" and for this message I want it to be named "Test Status Bot" which is working perfectly find via the web API.

2. Rich messages, I am using attachments and they are only available on web API, not RTM.

I can just do without the typing indicator, I thought it would be pretty cool for while my bot fetches data from an async source but if it's going to stick around after I've sent the response then it moves from being cool to being mislead (as in: "Huh, it says the bot is still typing but it never said anything else"). Also the typing indicator doesn't appear to offer a way to re-name it. So even though "Test Status Bot" is who the message comes from the typing indicator says "Generic Chat Bot" still.

I fully expect this to be closed under "we don't support this" or similar and that is fine, I just wanted to ask if there was a way to send a followup "typingStopped" type message. I'll still have the bot name mismatch issue but the typing indicator is really cool for increasing the immersive nature of chat bots.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
@joshstrange thanks for asking the question. unfortunately, the answer is exactly what you expected - we don't support a `"typingStopped"`-like message on RTM, and don't have any plans to add more message types to RTM. As you know, the Web API can do much more than RTM when it comes to sending message, so that's where I'd recommend you stick.

I think its interesting that the typing indicator is so important to your desired user experience. Out of curiosity, how long does your app typically spend in "typing" mode before the response is ready? Most bots I've seen can prepare the actual response in less than 3 seconds, and at that point, its not that beneficial to me as a user to see "Generic Chat Bot is typing...". If it gets longer than that (>5 seconds), I can see how it is important to let the user know something is happening. You *could* (I know its less similar to a human user) send a message right away that subtly says your bot is typing (or thinking or whatever) in an italics font so its not to be confused with an actual message. Then when the actual response is ready, you could either update that message, or delete it and send the actual message.

Another strategy could be to use Interactive Messages (buttons, menus, dialogs, etc) instead of a conversational UI. For example, when Slack shows the user a button, the message is in an inactive state (all interactive elements are disabled) until the app has responded. This is the kind of cue a user understands as "it's still performing the action". Another benefit of this strategy is that it improves the user experience by allowing the user to type less (which can be especially tricky on mobile).

Sorry I couldn't give you the answer you wanted, but I'm glad you asked because I'm sure others have the same question and I'll be able to refer to this message later 😄 .

**Comment by adam-experience** [comment]
@aoberoi I was just wondering about this kind of functionality for a couple reasons:
- More humanizing / engaging experience with the bot
- Building anticipation for the response

I'd love to know if anything has changed.
