### ISSUE TITLE
Support Slash Commands in interactive-messsages package

### ISSUE THREAD

**Issue by malonecm** [slackapi/node-slack-sdk#708]
### Description

Is there any reason why @slack/interactive-messages does not also support Slash commands? It would be very nice to be able to move my older code that is validating using the legacy Verification Token to @slack/interactive-messages and the message adapter, where I could do something like adapter.action({ type: 'slash_command', callbackId: '/mycommand'}, (payload, response) => {... }); or adapter.slashCommand("/mycommand", ...) if you do not want to gum up the action matching constraints, and then the library handles validation the slack signing secret properly then routes to my callback. 

As it is, I always end up just being lazy and using the legacy Verification Token because then I can just req.body.token === legacyVerificationToken and get on with it instead of validating the hmac properly. I feel slightly guilty about it.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by aoberoi** [comment]
> As it is, I always end up just being lazy and using the legacy Verification Token because then I can just req.body.token === legacyVerificationToken and get on with it instead of validating the hmac properly. I feel slightly guilty about it.

@malonecm good! you should feel guilty! (😆 just kidding)

But really, I'm glad you're doing some verification, which is way **way** better than none. Many developers take the temptation to skip this in the pursuit of getting something working quickly and then they never revisit it.

I think this is an interesting request. The `@slack/events-api` package exports a `verifyRequestSignature` function, specifically for use cases like this one. There isn't a good reason why that isn't also exported from `@slack/interactive-messages`, so we made this issue to track it: https://github.com/slackapi/node-slack-interactive-messages/issues/82.

The APIs (methods) you've proposed do look interesting, too. I think they are out of scope for that package because slash commands aren't considered interactive messages.

But I totally understand the temptation to just group this functionality into the same package because its so similar. In fact, I'm also tempted to combine the `@slack/events-api` package with it because its also so similar. While I'm going to stick to my opinion that its out of scope for now, I think that in the future we should be considering if we should pair these packages down into fewer (maybe just one) package(s). The motivation for making `@slack/interactive-messages` and `@slack/events-api` separate was to help guide people to the right package since the names more clearly match what's documented on api.slack.com, and to make sure you don't take on large dependencies whose code you won't need (if you're only building with the Events API, but do nothing with Interactive Messages, why should you have that code in your `node_modules`?). I think these reasons might not be strong enough to keep the packages separate much longer.

**Comment by aoberoi** [comment]
closing as out of scope. please feel free to keep discussing.
