### ISSUE TITLE
provide an rtm method to force disconnect/reset state

### ISSUE THREAD

**Issue by travisghansen** [slackapi/node-slack-sdk#710]
### Description

I've seen some pretty crazy behavior in a short period of time leveraging the sdk where disconnects have left me in a perpetual state of `connecting`.  Subsequently, issuing `disconnect()` results in a perpetual state of `disconnecting`.  Unless/until the issues can be resolved I'd like to have an option to forcefully tear down everything and then re-issue a `start()` with a clean slate.

With the above request in place I could implement an independent 'watchdog' process to watch for a long-running `connecting` state and eventually say "ok, let's start over" without losing all the created listeners etc (ie: trying to completely destroy the instance and re-setup listeners, initialize things, etc, etc).

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

`@slack/client` version:4.9.0

node version: v6.16.0

OS version(s): node-red docker image

#### Steps to reproduce:

1. sleep computer (or kill connectivity)
2. awake computer (or apply connectivity)
3. perpetual `connecting` state

#### Expected result:

Connection when connectivity is restored.

#### Actual result:

Perpetual state of `connecting`.  It seems to be intermittent so it doesn't happen all the time :(

**Comment by aoberoi** [comment]
> With the above request in place I could implement an independent 'watchdog' process to watch for a long-running `connecting` state and eventually say "ok, let's start over" without losing all the created listeners etc (ie: trying to completely destroy the instance and re-setup listeners, initialize things, etc, etc).

This approach doesn't seem like a solution to me. What's to say that the way you initialized things (added listeners, toggled configuration, etc) isn't causing the issue in the first place? Instead of treating the symptom, I'm more interested in fixing (or at least understanding) the issue, so that the symptoms don't occur.

I'm not super familiar with `node-red` (although I'd like to learn!), but maybe we should try eliminating that from the equation to see if it still occurs. It seems like you able to reliably able to reproduce the perpetual `connecting` state. If you use the same steps in another context (outside a docker container, or using a more generic docker container like `ubuntu`), does the same issue occur?

If its still occurring, we can keep trying to reduce the variables until I (or anyone else) can also reproduce the issue, and then we can figure out what an appropriate fix would be. This type of behavior is meant to never occur, and its exactly why we have `autoReconnect` in place. The next step would be to [turn on `DEBUG` logging](https://slack.dev/node-slack-sdk/rtm_api#customizing-the-logger) to see if we can get any more useful info out of the process.

If it no longer occurs outside the `node-red` environment, there's likely some interaction that we haven't accounted for. I'm still happy to keep investigating and getting my hands a little more dirty on the `node-red` side of things.

**Comment by travisghansen** [comment]
@aoberoi yeah I agree it's a hack...just assumed the issue may be deeper than even your library.  I'll try to get some debug logs setup and see if I can get it to reproduce but it's tough.  That's what's even tougher is `node-red` is meant to be a long-running process so random (or not 100% bullet proof) on a long running process of that nature is challenging.

I'm confident it's not in `node-red` as other connection-based services seem to reconnect without issue etc.

My connection process is as generic as it gets: `this.rtmClient = new RTMClient(this.credentials.token);`
Full code is here for review if you care: https://github.com/travisghansen/node-red-slack/blob/master/slackpost.js

**Comment by aoberoi** [comment]
Thanks @travisghansen, looking forward to seeing those logs or hearing more when the issue comes up again.

**Comment by travisghansen** [comment]
@aoberoi I've been watching this pretty closely and things appear to be in somewhat decent shape.  I've had some occasions where the time it took slack to reconnect was substantially longer than some others.  Is there a timer that keeps doubling the time between tries or something of that nature?  What's the max it should take after connectivity has been restored?

**Comment by aoberoi** [comment]
@travisghansen yes, there is some retry logic with exponential backoff when the `rtm.connect` method doesn't succeed in obtaining a websocket URL to connect to. you can disable this by initializing an RTMClient like this:

```javascript
const rtm = new RTMClient(token, {
  retryConfig: {
    retries: 0,
  },
});
```

If you want to keep retrying around, but want a different policy, you can do that too. You just need to describe your policy using [the options described by the `retry` package](https://github.com/tim-kos/node-retry#retrytimeoutsoptions).

the default policy will maxes out at 30 minutes.

**Comment by travisghansen** [comment]
@aoberoi what exactly maxes out at 30 minutes?  The time between tries? Or it completely gives up and will not attempt another retry after 30 total minutes of lost connectivity?

Is it possibly to retry infinitely?  Ideally I'd have something like:
1. retry `Infinity`
1. start with `X` seconds between retries
1. exponentially increase from `X` up to `Y`

For example, retry every 5 seconds and max out at 60 seconds between retries, and do it forever.  What would that look like?

Thanks!

**Comment by aoberoi** [comment]
Sorry for being a little ambiguous, 30 minutes is the max time between retries. However, with the maximum number of retries at 10 (the default), I just did [the summation on Wolfram Alpha](https://www.wolframalpha.com/input/?i=(Sum%5B1000*2%5Ek,+%7Bk,+0,+9%7D%5D)+%2F+(1000+*+60)) and it turns out that the final attempt would happen after around 17 minutes. That means it would completely give up after 17 minutes.

The policy you described can be achieved using the following code:

```
const rtm = new RTMClient(token, {
  retryConfig: {
    retries: Infinity,
    minTimeout: 5 * 1000,
    maxTimeout: 60 * 1000,
  },
});
```

**Comment by travisghansen** [comment]
@aoberoi the above produces this for me:
```
nodered_1                 | FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
nodered_1                 | 
nodered_1                 | <--- Last few GCs --->
nodered_1                 | 
nodered_1                 |     1384 ms: Scavenge 67.0 (89.7) -> 56.1 (92.7) MB, 6.3 / 0.0 ms [allocation failure].
nodered_1                 |     1546 ms: Mark-sweep 100.1 (133.8) -> 80.7 (126.4) MB, 5.4 / 0.0 ms (+ 33.3 ms in 6 steps since start of marking, biggest step 12.5 ms) [GC interrupt] [GC in old space requested].
nodered_1                 |     3118 ms: Mark-sweep 748.8 (794.7) -> 545.4 (589.2) MB, 12.5 / 0.0 ms (+ 29.1 ms in 2 steps since start of marking, biggest step 29.1 ms) [GC interrupt] [GC in old space requested].
nodered_1                 | 
nodered_1                 | 
nodered_1                 | <--- JS stacktrace --->
nodered_1                 | 
nodered_1                 | ==== JS stack trace =========================================
nodered_1                 | 
nodered_1                 | Security context: 0xbdf8dbcf781 <JS Object>
nodered_1                 |     2: timeouts [/data/node_modules/node-red-slack/node_modules/retry/lib/retry.js:~12] [pc=0x6d11699e0c] (this=0x1d3dfc3f83d9 <an Object with map 0x45ca1a34f59>,options=0x310fe493efc9 <an Object with map 0x146ee837e121>)
nodered_1                 |     3: operation [/data/node_modules/node-red-slack/node_modules/retry/lib/retry.js:4] [pc=0x6d1169719a] (this=0x1d3dfc3f83d9 <an Object with map 0x45ca1a34f59>,options=0x310fe...
nodered_1                 | 
nodered_1                 |  1: node::Abort() [node-red]
nodered_1                 |  2: 0x7d017c [node-red]
nodered_1                 |  3: v8::Utils::ReportApiFailure(char const*, char const*) [node-red]
nodered_1                 |  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node-red]
nodered_1                 |  5: v8::internal::Heap::AllocateUninitializedFixedDoubleArray(int, v8::internal::PretenureFlag) [node-red]
nodered_1                 |  6: v8::internal::Factory::NewFixedDoubleArray(int, v8::internal::PretenureFlag) [node-red]
nodered_1                 |  7: 0xb67a50 [node-red]
nodered_1                 |  8: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node-red]
nodered_1                 |  9: 0x6d10b079a7
```

Looking at `retry-policies.ts` maybe I should be not setting `retries` and instead do this `forever: true,`?

**Comment by aoberoi** [comment]
I’ll take a closer look at the source of `retry` to figure out why this policy would affect memory allocation in any meaningful way. 

The `forever` option sounds like it’s for repeating the intervals (from short to long) when the `maxTimeout` is reached.

**Comment by aoberoi** [comment]
Ah-hah! It looks like `Infinity` would make this an infinite loop: 
https://github.com/tim-kos/node-retry/blob/88548b9cd3b00948bd5cb4c4e460c2c8aacb85ae/lib/retry.js#L33

Would it be reasonable in your case to just define some finite but really long max timeout? Since the implementation statically calculates all the timeout lengths, I think this isn’t something we can provide. Also, if repeating the pattern is a reasonable way for you to get indefinite retrying, the `forever` option would make sense.

**Comment by travisghansen** [comment]
@aoberoi I'd rather have true *forever* in whatever form it takes.  I have instances of `Node-RED` that run for months/years on end without being restarted.  It's important to have reconnects happen with 100% assurance.

If you could send over a true *forever* scenario (whatever it looks like) that would be great.  I'm unclear how `forever` and `retries` conceptually differ.  Ultimately it doesn't *really* matter to me as long as I can get something that will retry as long as it has to...including the original request of this issue, implementing a watchdog outside the library if absolutely necessary.

**Comment by aoberoi** [comment]
The following should suit your needs:

```
const rtm = new RTMClient(token, {
  retryConfig: {
    forever: true,
    minTimeout: 5 * 1000,
    maxTimeout: 60 * 1000,
  },
});
```

**Comment by travisghansen** [comment]
@aoberoi for others stumbling across this in the future, how do `retries` and `forever` correlate?

**Comment by aoberoi** [comment]
I tried answering this above.

> The `forever` option sounds like it’s for repeating the intervals (from short to long) when the maxTimeout is reached.

The `retries` option is the number of retries in the "pattern", while `forever: true` tells the package that it can repeat the "pattern" over and over.

**Comment by travisghansen** [comment]
@aoberoi ah.  Thanks!
