### ISSUE TITLE
Add more useful messages to Web Client Debug

### ISSUE THREAD

**Issue by iancward** [slackapi/node-slack-sdk#766]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug / Enhancement
In their current state, debug logging for Web Client requests is effectively useless, telling you that a request was completed but not giving any context at all. For example:
```
debug: BaseAPIClient _callTransport end
```

I understand that you probably won't want to log the entire body or response, but at the very least, the API method being called, response code, and response time would be much more useful. If it was a non-200 response, you can probably safely log the full response.

Something like this would be extremely beneficial when using third-party module code that may not have reasonably good logging of its own.

**Comment by aoberoi** [comment]
hi @iancward 👋 

i noticed the error message you provided is produced from the `v3.x` versions of `@slack/client`. unfortunately, that line of releases has been End of Life (EOL) since May 2018. (FYI: Our [support schedule](https://github.com/slackapi/node-slack-sdk/wiki/Support-Schedule) has details regarding how we do EOL). this means we won't be pushing any changes to that would affect the releases you're using until you upgrade to something more recent (5.x preferrably).

its likely that you (and others who might want this change) are coming over from `hubot-slack`, where `v3.x` of `@slack/client` is a dependency. we don't have any current plans to update `hubot-slack` to a more recent version of this package. we could have a more detailed discussion about this, but its off-topic for this issue.

if you're still open to it, let's keep this issue open and discuss it as a feature request for our most recent version.

i have two ideas about how we can provide this feature:
1. log the request and response body under the `DEBUG` log level
2. add a new log level, call it `VERBOSE`, and log the request and response body under that level

currently, i'm partial to option (2) because for any users who many have taken the risk to use the `DEBUG` log level in production already, the addition of a new log level wouldn't affect them. this can be a security issue since request and response bodies typically include sensitive information (tokens, user PII, etc).

what do you think?

**Comment by misscoded** [comment]
We hope that the above suggestion has helped resolve this issue, but if that's not the case, feel free to comment and we'll revisit!
