### ISSUE TITLE
Disable event signature verification for testing?

### ISSUE THREAD

**Issue by Moglum** [slackapi/node-slack-sdk#770]
### Description

Is there an option to conditionally disable event request signature verification performed by the EventAdapter? 

This could be quite useful for writing local tests - sending an unsigned testing event wouldn't throw the SLACKHTTPHANDLER_REQUEST_SIGNATURE_VERIFICATION_FAILURE error.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
@Moglum There isn't an option like the one you're asking for currently.

For testing, we typically see developers create a fake request, signed by a fake signing secret so that this sort of problem is avoided. This technique can be seen in the project's own tests, specifically in the `createRequest()` helper: https://github.com/slackapi/node-slack-sdk/blob/master/packages/events-api/test/helpers.js

Its used a number of times in the tests here: https://github.com/slackapi/node-slack-sdk/blob/master/packages/events-api/test/unit/test-http-handler.js

Alternatively, you can structure your app so that you can unit test your handlers without having to send data through the adapter. This would be true unit testing since it wouldn't depend on the behavior of the adapter.

Would these strategies suit your needs?

**Comment by Moglum** [comment]
Ankur,
I will take a look at how it's done in the tests. But I think it will be a cleaner solution to slightly refactor my code and unit test just the handler logic.

Thank you very much for the quick reply, I got what I needed :thumbsup:
