### ISSUE TITLE
Confirmation Box Not Working

### ISSUE THREAD

**Issue by awcchungster** [slackapi/node-slack-sdk#781]
### Description

I'm trying to add a dialog box to confirm a button click / dropdown in interactive messages.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x ] question

### Requirements
* [ x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x ] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
@slack/interactive-messages version:
node version:
OS version(s):

#### Steps to reproduce:

1. Visit the [interactive message builder featuring thai food](https://api.slack.com/tools/block-kit-builder?blocks=%5B%0A%09%7B%0A%09%09%22type%22%3A%20%22section%22%2C%0A%09%09%22text%22%3A%20%7B%0A%09%09%09%22type%22%3A%20%22mrkdwn%22%2C%0A%09%09%09%22text%22%3A%20%22Hello%2C%20Assistant%20to%20the%20Regional%20Manager%20Dwight!%20*Michael%20Scott*%20wants%20to%20know%20where%20you%27d%20like%20to%20take%20the%20Paper%20Company%20investors%20to%20dinner%20tonight.%5Cn%5Cn%20*Please%20select%20a%20restaurant%3A*%22%0A%09%09%7D%0A%09%7D%2C%0A%09%7B%0A%09%09%22type%22%3A%20%22divider%22%0A%09%7D%2C%0A%09%7B%0A%09%09%22type%22%3A%20%22section%22%2C%0A%09%09%22text%22%3A%20%7B%0A%09%09%09%22type%22%3A%20%22mrkdwn%22%2C%0A%09%09%09%22text%22%3A%20%22*Farmhouse%20Thai%20Cuisine*%5Cn%3Astar%3A%3Astar%3A%3Astar%3A%3Astar%3A%201528%20reviews%5Cn%20They%20do%20have%20some%20vegan%20options%2C%20like%20the%20roti%20and%20curry%2C%20plus%20they%20have%20a%20ton%20of%20salad%20stuff%20and%20noodles%20can%20be%20ordered%20without%20meat!!%20They%20have%20something%20for%20everyone%20here%22%0A%09%09%7D%2C%0A%09%09%22accessory%22%3A%20%7B%0A%09%09%09%22type%22%3A%20%22image%22%2C%0A%09%09%09%22image_url%22%3A%20%22https%3A%2F%2Fs3-media3.fl.yelpcdn.com%2Fbphoto%2Fc7ed05m9lC2EmA3Aruue7A%2Fo.jpg%22%2C%0A%09%09%09%22alt_text%22%3A%20%22alt%20text%20for%20image%22%0A%09%09%7D%0A%09%7D%2C%0A%09%7B%0A%09%09%22type%22%3A%20%22section%22%2C%0A%09%09%22text%22%3A%20%7B%0A%09%09%09%22type%22%3A%20%22mrkdwn%22%2C%0A%09%09%09%22text%22%3A%20%22*Kin%20Khao*%5Cn%3Astar%3A%3Astar%3A%3Astar%3A%3Astar%3A%201638%20reviews%5Cn%20The%20sticky%20rice%20also%20goes%20wonderfully%20with%20the%20caramelized%20pork%20belly%2C%20which%20is%20absolutely%20melt-in-your-mouth%20and%20so%20soft.%22%0A%09%09%7D%2C%0A%09%09%22accessory%22%3A%20%7B%0A%09%09%09%22type%22%3A%20%22image%22%2C%0A%09%09%09%22image_url%22%3A%20%22https%3A%2F%2Fs3-media2.fl.yelpcdn.com%2Fbphoto%2Fkorel-1YjNtFtJlMTaC26A%2Fo.jpg%22%2C%0A%09%09%09%22alt_text%22%3A%20%22alt%20text%20for%20image%22%0A%09%09%7D%0A%09%7D%2C%0A%09%7B%0A%09%09%22type%22%3A%20%22section%22%2C%0A%09%09%22text%22%3A%20%7B%0A%09%09%09%22type%22%3A%20%22mrkdwn%22%2C%0A%09%09%09%22text%22%3A%20%22*Ler%20Ros*%5Cn%3Astar%3A%3Astar%3A%3Astar%3A%3Astar%3A%202082%20reviews%5Cn%20I%20would%20really%20recommend%20the%20%20Yum%20Koh%20Moo%20Yang%20-%20Spicy%20lime%20dressing%20and%20roasted%20quick%20marinated%20pork%20shoulder%2C%20basil%20leaves%2C%20chili%20%26%20rice%20powder.%22%0A%09%09%7D%2C%0A%09%09%22accessory%22%3A%20%7B%0A%09%09%09%22type%22%3A%20%22image%22%2C%0A%09%09%09%22image_url%22%3A%20%22https%3A%2F%2Fs3-media2.fl.yelpcdn.com%2Fbphoto%2FDawwNigKJ2ckPeDeDM7jAg%2Fo.jpg%22%2C%0A%09%09%09%22alt_text%22%3A%20%22alt%20text%20for%20image%22%0A%09%09%7D%0A%09%7D%2C%0A%09%7B%0A%09%09%22type%22%3A%20%22divider%22%0A%09%7D%2C%0A%09%7B%0A%09%09%22type%22%3A%20%22actions%22%2C%0A%09%09%22elements%22%3A%20%5B%0A%09%09%09%7B%0A%09%09%09%09%22type%22%3A%20%22button%22%2C%0A%09%09%09%09%22text%22%3A%20%7B%0A%09%09%09%09%09%22type%22%3A%20%22plain_text%22%2C%0A%09%09%09%09%09%22text%22%3A%20%22Farmhouse%22%2C%0A%09%09%09%09%09%22emoji%22%3A%20true%0A%09%09%09%09%7D%2C%0A%09%09%09%09%22value%22%3A%20%22click_me_123%22%0A%09%09%09%7D%2C%0A%09%09%09%7B%0A%09%09%09%09%22type%22%3A%20%22button%22%2C%0A%09%09%09%09%22text%22%3A%20%7B%0A%09%09%09%09%09%22type%22%3A%20%22plain_text%22%2C%0A%09%09%09%09%09%22text%22%3A%20%22Kin%20Khao%22%2C%0A%09%09%09%09%09%22emoji%22%3A%20true%0A%09%09%09%09%7D%2C%0A%09%09%09%09%22value%22%3A%20%22click_me_123%22%0A%09%09%09%7D%2C%0A%09%09%09%7B%0A%09%09%09%09%22type%22%3A%20%22button%22%2C%0A%09%09%09%09%22text%22%3A%20%7B%0A%09%09%09%09%09%22type%22%3A%20%22plain_text%22%2C%0A%09%09%09%09%09%22text%22%3A%20%22Ler%20Ros%22%2C%0A%09%09%09%09%09%22emoji%22%3A%20true%0A%09%09%09%09%7D%2C%0A%09%09%09%09%22value%22%3A%20%22click_me_123%22%0A%09%09%09%7D%0A%09%09%5D%0A%09%7D%0A%5D).
2. Try to add the confirm code in the one of the blocks section where actions are done

> {  
>       "type":"section",
>       "text":{  
>          "type":"mrkdwn",
>          "text":"Action:"
>       },
>       "accessory":{  
>          "type":"static_select",
>          "placeholder":{  
>             "type":"plain_text",
>             "emoji":true,
>             "text":"Select an option"
>          },
>          "options":[  
>             {  
>                "text":{  
>                   "type":"plain_text",
>                   "emoji":true,
>                   "text":"Approve"
>                },
>                "value":"-approve",
>                "confirm":{  
>                   "title":{  
>                      "type":"plain_text",
>                      "text":"Are you sure?"
>                   },
>                   "text":{  
>                      "type":"plain_text",
>                      "text":"You're about to approve."
>                   },
>                   "confirm":{  
>                      "type":"plain_text",
>                      "text":"Yes"
>                   },
>                   "deny":{  
>                      "type":"plain_text",
>                      "text":"No"
>                   }
>                }
>             },
>             {  
>                "text":{  
>                   "type":"plain_text",
>                   "emoji":true,
>                   "text":"Block - Fraud"
>                },
>                "value":"-block_fraud",
>                "confirm":{  
>                   "title":{  
>                      "type":"plain_text",
>                      "text":"Are you sure?"
>                   },
>                   "text":{  
>                      "type":"plain_text",
>                      "text":"You're about to block for fraud."
>                   },
>                   "confirm":{  
>                      "type":"plain_text",
>                      "text":"Yes"
>                   },
>                   "deny":{  
>                      "type":"plain_text",
>                      "text":"No"
>                   }
>                }
>             },
>             {  
>                "text":{  
>                   "type":"plain_text",
>                   "emoji":true,
>                   "text":"Block - Wrong Info"
>                },
>                "value":"-block_wrong_info",
>                "confirm":{  
>                   "title":{  
>                      "type":"plain_text",
>                      "text":"Are you sure?"
>                   },
>                   "text":{  
>                      "type":"plain_text",
>                      "text":"You're about to block for wrong info."
>                   },
>                   "confirm":{  
>                      "type":"plain_text",
>                      "text":"Yes"
>                   },
>                   "deny":{  
>                      "type":"plain_text",
>                      "text":"No"
>                   }
>                }
>             }
>          ],
>          "action_id":"escalation_response"
>       }
>    }
> 

3. Try to compile the interactive message
#### Expected result:

It should create an interactive message with a dialog confirmation box, but it doesn't 

#### Actual result:

Doesn't allow confirm

**Comment by awcchungster** [comment]
@shanedewael @aoberoi Reopening this from [Issue](https://github.com/slackapi/node-slack-interactive-messages/issues/93) because it failed in testing.

**Comment by awcchungster** [comment]
bump. @shanedewael  @aoberoi

**Comment by shanedewael** [comment]
Hey @awcchungster 👋 the problem you're reporting would be an issue with Block Kit, not any of our developer tools. In the future, issues like this should be sent to developers@slack.com — they'll be a lot faster to respond to platform issues like this.

I tested out your payload and you placed the `confirm` object in the wrong spot. It should always be at the top level of an action element (on the same level as the `action_id`) rather than associated with each `option` in the select menu. 

[Here's a link to a working version of your payload in the Builder](https://api.slack.com/tools/block-kit-builder?blocks=%5B%0A%09%7B%0A%09%09%22type%22%3A%20%22section%22%2C%0A%09%09%22text%22%3A%20%7B%0A%09%09%09%22type%22%3A%20%22mrkdwn%22%2C%0A%09%09%09%22text%22%3A%20%22Action%3A%22%0A%09%09%7D%2C%0A%09%09%22accessory%22%3A%20%7B%0A%09%09%09%22type%22%3A%20%22static_select%22%2C%0A%09%09%09%22placeholder%22%3A%20%7B%0A%09%09%09%09%22type%22%3A%20%22plain_text%22%2C%0A%09%09%09%09%22text%22%3A%20%22Select%20an%20option%22%2C%0A%09%09%09%09%22emoji%22%3A%20true%0A%09%09%09%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22confirm%22%3A%20%7B%0A%20%20%20%20%09%09%09%22title%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%09%09%09%22type%22%3A%20%22plain_text%22%2C%0A%20%20%20%20%20%20%20%20%09%09%09%22text%22%3A%20%22Are%20you%20sure%3F%22%0A%20%20%20%20%09%09%09%7D%2C%0A%20%20%20%20%09%09%09%22text%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%09%09%09%22type%22%3A%20%22plain_text%22%2C%0A%20%20%20%20%20%20%20%20%09%09%09%22text%22%3A%20%22You%27re%20about%20to%20approve.%22%0A%20%20%20%20%09%09%09%7D%2C%0A%20%20%20%20%09%09%09%22confirm%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%09%09%09%22type%22%3A%20%22plain_text%22%2C%0A%20%20%20%20%20%20%20%20%09%09%09%22text%22%3A%20%22Yes%22%0A%20%20%20%20%09%09%09%7D%2C%0A%20%20%20%20%09%09%09%22deny%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%09%09%09%22type%22%3A%20%22plain_text%22%2C%0A%20%20%20%20%20%20%20%20%09%09%09%22text%22%3A%20%22No%22%0A%20%20%20%20%09%09%09%7D%0A%09%09%09%7D%2C%0A%09%09%09%22options%22%3A%20%5B%0A%09%09%09%09%7B%0A%09%09%09%09%09%22text%22%3A%20%7B%0A%09%09%09%09%09%09%22type%22%3A%20%22plain_text%22%2C%0A%09%09%09%09%09%09%22text%22%3A%20%22Approve%22%2C%0A%09%09%09%09%09%09%22emoji%22%3A%20true%0A%09%09%09%09%09%7D%2C%0A%09%09%09%09%09%22value%22%3A%20%22-approve%22%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09%22text%22%3A%20%7B%0A%09%09%09%09%09%09%22type%22%3A%20%22plain_text%22%2C%0A%09%09%09%09%09%09%22text%22%3A%20%22Block%20-%20Wrong%20Info%22%2C%0A%09%09%09%09%09%09%22emoji%22%3A%20true%0A%09%09%09%09%09%7D%2C%0A%09%09%09%09%09%22value%22%3A%20%22-block_wrong_info%22%0A%09%09%09%09%7D%0A%09%09%09%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22action_id%22%3A%20%22escalation_response%22%0A%09%09%7D%0A%09%7D%0A%5D).

**Comment by awcchungster** [comment]
@shanedewael  This doesn't work. When I do a reject, it gives the same dialogue box of approve, rather than showing block.

**Comment by shanedewael** [comment]
@awcchungster As of right now, it's not possible to have different confirmation text based on what the user selected in a select. I see how updating the confirmation text based on the user's choice could be valuable — I can definitely send the feedback along to our product team.

For now, you could use two buttons since they can each have their own confirm dialog, or broaden the dialog box to say something like "Are you sure? The action you select is final". Sorry this has been causing trouble.

**Comment by seratch** [comment]
Hi, I know probably this is very late but let me add a bit more information here.

As Shay described above, the `confirm` component has only simple functionalities. But if you utilize multiple modal views (updating a single modal view by `response_action: update` in a `view_submission` response or calling `views.update` when receiving `block_actions` requests), it may be possible to realize a better user experience with richer UI components. Please refer to https://api.slack.com/surfaces/modals/using for details.

If you don't mind, I would like to close this issue as there is no further information we can share with you at this moment. Please allow me to close this after waiting for your response for a while.
