### ISSUE TITLE
webhook api > overridable/multiple URLs based on webhook

### ISSUE THREAD

**Issue by naseemkullah** [slackapi/node-slack-sdk#857]
### Description

Hi,

I would like to have various Slack webhook URLs, and depending on contents of the incoming webhook, send it to the corresponding URL.

Maybe with a config along the lines of:

```
"SLACK_WEBHOOK_RULES": [{
      "rule": {
        "foo": "bar"
      },
      "slack_webhook_url": "https://hooks.slack.com/services/XYZ"
    },
    {
      "rule": {
        "baz": "qaz",
        "maybesomething": "maybesomethingelse"
      },
      "slack_webhook_url": "https://hooks.slack.com/services/ZZZ"
    }
  ]
```

Is there anyway of achieving this now?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [ ] I don't know

**Comment by naseemkullah** [comment]
bump

**Comment by aoberoi** [comment]
hi @naseemkullah 👋. i'm not too sure what the `rules` in your example are used for.

it seems like you'd like to declaratively set up your webhooks in another application. that makes sense, but would be logic that you should add to the application. this library cannot know how you prefer to read those configurations and where they are stored.

i don't think you should commit the webhook URLs into your codebase because they are essentially secrets. anyone who has access to your webhook URL has access to post a message into your channel. we recommend keeping them outside your code and injecting them into your application using environment variables (or a similar configuration technique).

let's assume you've read that configuration from some place and its in a variable called `config`. here's an example of how you might handle some event by iterating over those webhooks to send a message to more than one destination:

```js
const { IncomingWebhook } = require('@slack/webhook');
const webhooks = config.SLACK_WEBHOOK_RULES;

function handleSomeEvent(event) {
	return Promise.all(webhooks.map((webhook) => {
	  if (rulesMatch(webhook.rule, event)) {
        return new IncomingWebhook(webhook.slack_webhook_url).send({
          text: event.text,
        });
      }
	}))
    .then(() => console.log('sent notifications'))
    .catch(console.error);
}
```

**Comment by naseemkullah** [comment]
Thanks @aoberoi! If I understand correctly, mapping to different webhook URLs  based on event data (what I referred to as "rule") is something that should be done in the application code and there is no formal way of achieving this within this lib?

**Comment by aoberoi** [comment]
that's correct! i'll close this issue now because it seems like you're set. if you need more help, feel free to comment again, or open another issue.

**Comment by naseemkullah** [comment]
Perfect, thanks @aoberoi
