### ISSUE TITLE
Formatting messages does not support markdown anymore?

### ISSUE THREAD

**Issue by FredyC** [slackapi/node-slack-sdk#926]
### Description

It seems that Slack has changed how messages are formatted. When pasting a text `hello **world**` into any Slack window, it does not get transformed anymore as it used to and is displayed as-is. The same happens when sending a message through @slack/webhooks.

![image](https://user-images.githubusercontent.com/1096340/70323244-9a9f9a00-182c-11ea-8bcf-d09cf4b50475.png)

The official documentation hasn't caught up with that change just yet it seems. I am not sure how are we suppose to format messages.

I don't need any sort of interactive message, just a simple highlight of important pieces of information.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by stevengill** [comment]
Hey @FredyC,

A few possible things going on. 

Firstly, for bolding you only need one asterisk `*wolrd*`. Checkout our [formatting messages guide](https://api.slack.com/messaging/composing/formatting) to see the supported markup.

Slack released a new WYSIWYG messaging tool. This is the new default in the desktop client (and web browser). It looks like the following:

<img width="381" alt="WYSIWYG" src="https://user-images.githubusercontent.com/169536/70343920-4afda600-180d-11ea-93c4-cf4724f32e83.png">

When I copy and paste `hello *world*` into the WYSIWYG message box, it doesn't convert it to markup. To me, this seems like it could be a bug. If I am typing instead of copying, `hello *world*` does bold. 

If I [turn off WYSIWYG](https://slack.com/intl/en-ca/help/articles/360039953113) (going back to the original message box), copying and typing `hello *world*` both work.

Could you provide a quick sample of it not working with `@slack/webhooks` for you? It should work. Most text objects support it by setting the `type` to `mrkdwn`.

**Comment by FredyC** [comment]
You are right, when I copy & paste `hello *world*` into WYSIWYG, this message pops up and clicking on Apply does transform it correctly. So that was a mistake on my side to use a wrong markup.

![image](https://user-images.githubusercontent.com/1096340/70357122-6781f880-1876-11ea-8935-bfeb96adab74.png)

Using the same formatting works through webhook as well.

Silly me, not sure why I thought that `**` is correct format :)
